import { createContext, useContext, useEffect, useState } from 'react'
import type { ReactNode } from 'react'

const englishCatalog = {
  'brand.homeLabel': 'Honest Resume home',
  'brand.name': 'Honest Resume',
  'brand.tagline': 'A more honest way to get hired.',
  'demoAccess.title': 'Preparing the demo',
  'demoAccess.description': 'A quick security check protects this public demo from automated abuse. No account is required.',
  'demoAccess.verifying': 'Checking access…',
  'demoAccess.retry': 'Try the security check again',
  'locale.english': 'English',
  'locale.french': 'Français',
  'locale.persistenceFailure': 'Your language preference could not be saved.',
  'locale.unavailable': 'The interface language is unavailable.',
  'locale.switcherLabel': 'Language',
  'hero.title': 'Tailor your resume without inventing a thing.',
  'hero.lede': 'Build a focused resume from facts you have reviewed and approved.',
  'candidateJourney.eyebrow': 'Candidate Journey',
  'candidateJourney.title': 'One honest resume, shaped around the opportunity.',
  'candidateJourney.description': 'Keep your professional evidence private in this browser for a 24-hour Candidate Session while you move through three focused phases.',
  'candidateJourney.privateByDesign': 'Private by design',
  'candidateJourney.phasesLabel': 'Candidate Journey phases',
  'candidateJourney.sourceIntake': 'Source Intake',
  'candidateJourney.sourceIntakeDescription': 'Add the professional facts that can support your application.',
  'candidateJourney.jobMatch': 'Job Match',
  'candidateJourney.jobMatchDescription': 'Compare your evidence with one Job Posting.',
  'candidateJourney.tailoredResumePreparation': 'Tailored Resume Preparation',
  'candidateJourney.tailoredResumePreparationDescription': 'Prepare and export an evidence-backed resume.',
  'tailoredResume.ready': 'Tailored Resume ready',
  'tailoredResume.fallbackRole': 'Tailored Resume',
  'tailoredResume.valueProposition': 'Value Proposition',
  'tailoredResume.experiences': 'Experience',
  'tailoredResume.chronology.relevant': 'Relevant experience',
  'tailoredResume.chronology.context': 'Context experience',
  'tailoredResume.chronology.earlier': 'Earlier experience',
  'tailoredResume.section.skills': 'Skills',
  'tailoredResume.section.education': 'Education',
  'tailoredResume.section.languages': 'Languages',
  'tailoredResume.section.projects': 'Projects',
  'tailoredResume.section.certifications': 'Certifications',
  'tailoredResume.language': 'Resume language',
  'tailoredResume.languageAutomatic': 'Job Posting language',
  'tailoredResume.contactDetails': 'Local contact details',
  'tailoredResume.name': 'Name',
  'tailoredResume.email': 'Email',
  'tailoredResume.phone': 'Phone',
  'tailoredResume.editFields': 'Edit Tailored Resume fields',
  'tailoredResume.fieldLabel': 'Resume Field',
  'tailoredResume.saveField': 'Save wording',
  'tailoredResume.attestField': 'Attest as a new Candidate Fact',
  'tailoredResume.unsupportedField': 'This professional edit is not supported by the current Candidate Facts.',
  'tailoredResume.unsupportedFields': 'Resolve or attest each unsupported professional field before exporting.',
  'tailoredResume.hideField': 'Hide field',
  'tailoredResume.hiddenFields': 'Hidden fields',
  'tailoredResume.restoreField': 'Restore field',
  'tailoredResume.moveUp': 'Move up',
  'tailoredResume.moveDown': 'Move down',
  'tailoredResume.exportBlocked': 'Export is blocked while an unsupported professional field remains unresolved.',
  'candidateJourney.startSession': 'Start a Candidate Session',
  'candidateJourney.sessionActive': 'Candidate Session active',
  'candidateJourney.deleteSession': 'Delete Candidate Session',
  'candidateJourney.deleteDialogTitle': 'Delete Candidate Session?',
  'candidateJourney.deleteDialogDescription': 'This immediately removes the Candidate Session stored in this browser.',
  'candidateJourney.deleteCancel': 'Cancel',
  'candidateJourney.deleteConfirm': 'Delete session now',
  'candidateJourney.sessionDeleted': 'Candidate Session deleted from this browser.',
  'candidateJourney.expiredSessionDiscarded': 'Your expired Candidate Session was deleted from this browser.',
  'candidateJourney.incompatibleSessionDiscarded': 'An incompatible Candidate Session was deleted from this browser.',
  'candidateJourney.storageUnavailable': 'Candidate Session storage is unavailable.',
  'processingPolicy.title': 'Processing Policy',
  'processingPolicy.description': 'Review the active policy before any Candidate content is sent for model processing.',
  'processingPolicy.provider': 'Provider',
  'processingPolicy.purposes': 'Purposes',
  'processingPolicy.transmittedDataCategories': 'Data sent',
  'processingPolicy.retentionPolicy': 'Retention',
  'processingPolicy.storageBehavior': 'Storage',
  'processingPolicy.version': 'Policy version',
  'processingPolicy.grantConsent': 'Grant Processing Consent',
  'processingPolicy.consentGranted': 'Processing Consent granted for this policy.',
  'processingPolicy.purpose.extractEvidence': 'Extract and structure professional evidence',
  'processingPolicy.purpose.compareEvidence': 'Compare Candidate evidence with Job Posting requirements',
  'processingPolicy.purpose.writeResume': 'Write and validate supported Tailored Resume content',
  'processingPolicy.data.minimizedProfessionalContent': 'Minimized professional content',
  'processingPolicy.data.jobPostingContent': 'Job Posting content',
  'processingPolicy.data.candidateFacts': 'Candidate Facts needed for matching, writing, and validation',
  'processingPolicy.retentionValue': 'API inputs and outputs may be retained for abuse monitoring for up to 30 days, or longer when legally required.',
  'processingPolicy.storageValue': 'Candidate content remains browser-local; model requests are stateless with application storage disabled.',
  'sourceIntake.title': 'Complete your Source Intake',
  'sourceIntake.description': 'Upload a text-based PDF or DOCX, or paste professional text. Contact details stay in this browser.',
  'sourceIntake.pasteMethod': 'Paste text',
  'sourceIntake.uploadMethod': 'Upload PDF or DOCX',
  'sourceIntake.professionalText': 'Professional text',
  'sourceIntake.professionalTextPlaceholder': 'Paste your experience, projects, skills, education, languages, and certifications',
  'sourceIntake.sourceFile': 'Source Document',
  'sourceIntake.sourceFileHint': 'Choose a PDF or DOCX (maximum five pages)',
  'sourceIntake.submit': 'Build my Source Profile',
  'sourceIntake.ready': 'Your Source Profile is ready.',
  'sourceIntake.inspectProfile': 'Inspect Source Profile',
  'sourceIntake.hideProfile': 'Hide Source Profile',
  'sourceIntake.detailedProfile': 'Detailed Source Profile',
  'sourceIntake.ambiguities': 'Resolve Critical Ambiguities',
  'sourceIntake.answerAmbiguity': 'Save this answer',
  'sourceIntake.experiences': 'Experiences',
  'sourceIntake.projects': 'Projects',
  'sourceIntake.skills': 'Skills',
  'sourceIntake.education': 'Education',
  'sourceIntake.languages': 'Languages',
  'sourceIntake.certifications': 'Certifications',
  'sourceIntake.failure.ambiguity': 'This Critical Ambiguity is no longer available.',
  'sourceIntake.failure.storage': 'The Source Profile could not be saved in this browser.',
  'sourceIntake.failure.encrypted': 'This document is encrypted. Upload an unlocked copy or paste its text.',
  'sourceIntake.failure.empty': 'Add professional text before continuing.',
  'sourceIntake.failure.invalid': 'This document is invalid. Export a new PDF or DOCX and try again.',
  'sourceIntake.failure.oversized': 'Use a document of at most five pages and 5 MB, or paste up to 50,000 characters.',
  'sourceIntake.failure.consent': 'Grant Processing Consent before building the Source Profile.',
  'sourceIntake.failure.scanned': 'This PDF appears to be a scan. Use a PDF with selectable text or paste the text.',
  'sourceIntake.failure.extraction': 'The Source Profile could not be extracted. Your Candidate Session is unchanged; try again.',
  'sourceIntake.failure.unreadable': 'This document could not be read. Upload another copy or paste the text.',
  'sourceIntake.failure.unsupported': 'Only text-based PDF, DOCX, and pasted text are supported.',
  'jobMatch.title': 'Analyze one Job Posting',
  'jobMatch.description': 'Paste the posting or upload a text-based PDF or TXT. Employer noise and repeated wording will not inflate the result.',
  'jobMatch.pasteMethod': 'Paste text',
  'jobMatch.uploadMethod': 'Upload PDF or TXT',
  'jobMatch.textLabel': 'Job Posting text',
  'jobMatch.textPlaceholder': 'Paste the complete Job Posting',
  'jobMatch.fileLabel': 'Job Posting file',
  'jobMatch.fileHint': 'Choose a text-based PDF or TXT',
  'jobMatch.submit': 'Analyze this Job Posting',
  'jobMatch.targetRole': 'Target Role',
  'jobMatch.measurement': 'This score measures how strongly your Candidate Facts cover the explicit professional requirements. It is not a hiring probability.',
  'jobMatch.strengths': 'Three strongest matches',
  'jobMatch.gaps': 'Three priority gaps',
  'jobMatch.criticalReserve': 'Critical Requirement Reserve',
  'jobMatch.criticalReserve.clear': 'No critical requirement has an evidence reserve.',
  'jobMatch.criticalReserve.present': 'One or more critical requirements are partial or unsupported. Read these gaps before deciding to apply.',
  'jobMatch.constraints': 'Important Practical Constraints',
  'jobMatch.constraints.none': 'No explicit Practical Constraint was found.',
  'jobMatch.details': 'Complete requirement-to-evidence details',
  'jobMatch.importance.critical': 'Critical',
  'jobMatch.importance.central': 'Central',
  'jobMatch.importance.complementary': 'Complementary',
  'jobMatch.coverage.covered': 'Covered',
  'jobMatch.coverage.partially-covered': 'Partially covered',
  'jobMatch.coverage.uncovered': 'Uncovered',
  'jobMatch.sourceExcerpt': 'Exact source excerpt',
  'jobMatch.evidence': 'Candidate evidence',
  'jobMatch.evidence.none': 'No supporting Candidate Fact.',
  'jobMatch.failure.empty': 'Add Job Posting text before continuing.',
  'jobMatch.failure.invalid': 'This Job Posting file is invalid.',
  'jobMatch.failure.oversized': 'Use a Job Posting smaller than 5 MB and 100,000 characters.',
  'jobMatch.failure.scanned': 'This PDF appears to be a scan. Use a PDF with selectable text or paste the text.',
  'jobMatch.failure.unsupported': 'Only pasted text, text-based PDF, and TXT Job Postings are supported. URL scraping is not available.',
  'jobMatch.failure.unreadable': 'This Job Posting could not be read. Upload another copy or paste the text.',
  'jobMatch.failure.extraction': 'The Job Posting could not be analyzed. Your previous stable result is unchanged; try again.',
  'jobMatch.failure.evidence': 'Match Evidence could not be validated. Your previous stable result is unchanged; try again.',
  'jobMatch.failure.consent': 'Grant Processing Consent before analyzing a Job Posting.',
  'jobMatch.failure.storage': 'The Match Analysis could not be saved in this browser.',
  'jobMatch.enrichmentUnavailable': 'This requirement cannot accept Profile Enrichment.',
  'jobMatch.generation.denied': 'No relevant Candidate Fact supports an honest Tailored Resume.',
  'jobMatch.generation.eligible': 'Your evidence can support an honest Tailored Resume.',
  'jobMatch.generation.lowScoreWarning': 'A low Match Score is a warning, not a generation block.',
  'jobMatch.generation.normalizedAction': 'Use my normalized source resume — not tailored',
  'jobMatch.generation.normalizedNotice': 'Only a normalized version of your Source Profile is available. It will not use the Job Posting to claim tailoring.',
  'jobMatch.generation.tailoredAction': 'Prepare my Tailored Resume',
  'jobMatch.generation.normalizedDocumentTitle': 'NORMALIZED SOURCE RESUME — NOT TAILORED',
  'jobMatch.generation.normalizedContact': 'CONTACT',
  'jobMatch.generation.normalizedExperience': 'EXPERIENCE',
  'jobMatch.generation.normalizedExperienceFallback': 'Experience',
  'jobMatch.generation.normalizedProjects': 'PROJECTS',
  'jobMatch.generation.normalizedSkills': 'SKILLS',
  'jobMatch.generation.normalizedEducation': 'EDUCATION',
  'jobMatch.generation.normalizedLanguages': 'LANGUAGES',
  'jobMatch.generation.normalizedCertifications': 'CERTIFICATIONS',
  'jobMatch.generation.normalizedAdditional': 'ADDITIONAL VERIFIED INFORMATION',
  'jobMatch.generation.normalizedFileName': 'normalized-source-resume-not-tailored.txt',
  'jobMatch.generation.contact.address': 'Address',
  'jobMatch.generation.contact.date-of-birth': 'Date of birth',
  'jobMatch.generation.contact.email': 'Email',
  'jobMatch.generation.contact.personal-information': 'Personal information',
  'jobMatch.generation.contact.phone': 'Phone',
  'jobMatch.generation.contact.url': 'URL',
  'session.start': 'Start tailoring',
  'session.delete': 'Delete private session',
  'session.controlsLabel': 'Private session controls',
  'session.deleteDialogTitle': 'Delete private session?',
  'session.deleteDialogDescription': 'This immediately deletes this Candidate session from this browser and invalidates it in every open tab.',
  'session.deleteContentIntro': 'When present, the browser-local content removed includes:',
  'session.deleteSourceDocument': 'Source Document',
  'session.deleteSourceProfile': 'Source Profile',
  'session.deleteJobPosting': 'Job Posting',
  'session.deleteMatchAnalysis': 'Match Analysis',
  'session.deleteTailoredResume': 'Tailored Resume',
  'session.deletePhoto': 'Candidate-supplied photo',
  'session.deleteCancel': 'Cancel',
  'session.deleteConfirm': 'Delete session now',
  'session.loadFailure': 'Your private session could not be loaded.',
  'session.openFailure': 'The workflow could not be opened. Try again.',
  'session.deleteFailure': 'Your private session could not be deleted. Try again.',
  'sourceProfile.title': 'Build your Source Profile',
  'sourceProfile.importDescription': 'Your resume is the source of truth. Review the compact profile and correct only what needs changing.',
  'sourceProfile.methodLabel': 'Source Document method',
  'sourceProfile.pdfMethod': 'Text-based PDF',
  'sourceProfile.pdfDescription': 'Use an existing resume or LinkedIn PDF with selectable text. Scanned image-only PDFs cannot be read.',
  'sourceProfile.choosePdf': 'Choose PDF',
  'sourceProfile.noFileSelected': 'No PDF selected',
  'sourceProfile.selectedFile': 'Selected PDF:',
  'sourceProfile.textMethod': 'Paste professional text',
  'sourceProfile.textDescription': 'Paste professional experience, education, skills, languages, or projects.',
  'sourceProfile.textLabel': 'Professional text',
  'sourceProfile.textPlaceholder': 'Paste your professional information here',
  'sourceProfile.reviewText': 'Review pasted text',
  'sourceProfile.emptyTextFailure': 'Paste professional text before continuing.',
  'sourceProfile.reviewSurfaceTitle': 'Review outgoing Source Document',
  'sourceProfile.detectedTitle': 'Removed before processing',
  'sourceProfile.detectedNone': 'No common contact or sensitive personal information was detected.',
  'sourceProfile.sensitiveKind.email': 'Email address',
  'sourceProfile.sensitiveKind.phone': 'Phone number',
  'sourceProfile.sensitiveKind.url': 'Web address',
  'sourceProfile.sensitiveKind.address': 'Postal address',
  'sourceProfile.sensitiveKind.date-of-birth': 'Date of birth',
  'sourceProfile.sensitiveKind.personal-information': 'Personal information',
  'sourceProfile.outgoingLabel': 'Exact content that will be sent for extraction',
  'sourceProfile.saveContent': 'Save minimized content',
  'sourceProfile.noticeTitle': 'Processing notice',
  'sourceProfile.noticeText': 'OpenAI receives the minimized professional content shown above, later Job Posting content, and the Candidate Facts needed for matching and writing through stateless requests with storage disabled. Standard abuse-monitoring retention may still apply. This consent covers model operations during this 24-hour Candidate Session while the notice version remains current.',
  'sourceProfile.noticeVersion': 'Notice version:',
  'sourceProfile.confirmNotice': 'Confirm this processing notice',
  'sourceProfile.confirmAndExtract': 'Continue and analyze my resume',
  'sourceProfile.noticeConfirmed': 'Processing notice confirmed for this session.',
  'sourceProfile.extract': 'Extract professional facts',
  'sourceProfile.factsTitle': 'Check your imported profile',
  'sourceProfile.reviewProgress': 'Facts reviewed:',
  'sourceProfile.filterLabel': 'Filter facts by status',
  'sourceProfile.filterAll': 'All',
  'sourceProfile.filterEmpty': 'No facts match this filter.',
  'sourceProfile.showMore': 'Show more facts',
  'sourceProfile.batchTitle': 'Facts selected for batch confirmation',
  'sourceProfile.batchDescription': 'Review every fact in this visible list before confirming the batch.',
  'sourceProfile.batchConfirm': 'Confirm',
  'sourceProfile.conflictsTitle': 'Conflicts requiring resolution',
  'sourceProfile.conflictsDescription': 'Keep one proposition explicitly or reject a conflicting fact.',
  'sourceProfile.conflictsAnnouncement': 'conflicting facts requiring resolution.',
  'sourceProfile.factStates': 'Fact states:',
  'sourceProfile.select': 'Select',
  'sourceProfile.selectFact': 'Select',
  'sourceProfile.selectGroup': 'Select visible facts in this group',
  'sourceProfile.selectedFact': 'selected fact',
  'sourceProfile.selectedFacts': 'selected facts',
  'sourceProfile.confirmFact': 'Confirm fact',
  'sourceProfile.rejectFact': 'Reject fact',
  'sourceProfile.correctFact': 'Create correction',
  'sourceProfile.correctionLabel': 'Correct this information',
  'sourceProfile.resolveConflict': 'Keep this fact and resolve the conflict',
  'sourceProfile.unsupportedFailure': 'Choose a PDF file. Other Source Document formats are not supported yet.',
  'sourceProfile.encryptedPdfFailure': 'This PDF is password-protected. Unlock it or export an unprotected copy, then try again.',
  'sourceProfile.invalidPdfFailure': 'This file is not a valid PDF. Choose another PDF file.',
  'sourceProfile.textEmptyPdfFailure': 'This PDF contains no selectable text. Use a text-based PDF or paste your professional text instead.',
  'sourceProfile.unreadableFailure': 'This PDF could not be read completely. Choose another text-based PDF and try again.',
  'sourceProfile.browserCompatibilityFailure': 'This browser cannot read PDFs reliably. Update Safari, Chrome, or Firefox, or paste your professional text instead.',
  'sourceProfile.extractionFailure': 'Professional facts could not be extracted. Check the service configuration and try again.',
  'sourceProfile.failure': 'The Source Profile action failed. Check the PDF or configuration and try again.',
  'sourceProfile.kind.experience': 'Experience',
  'sourceProfile.kind.skill': 'Skill',
  'sourceProfile.kind.education': 'Education',
  'sourceProfile.kind.certification': 'Certification',
  'sourceProfile.kind.language': 'Language',
  'sourceProfile.kind.project': 'Project',
  'sourceProfile.status.extracted': 'Needs review',
  'sourceProfile.status.verified': 'From your resume',
  'sourceProfile.status.rejected': 'Rejected',
  'sourceProfile.status.superseded': 'Superseded',
  'jobPosting.title': 'Review your Job Posting',
  'jobPosting.inputLabel': 'Paste the Job Posting',
  'jobPosting.fileLabel': 'Or upload a PDF or TXT Job Posting',
  'jobPosting.analyze': 'Analyze this Job Posting',
  'jobPosting.review': 'Review this Job Posting',
  'jobPosting.historyTitle': 'Previously analyzed postings',
  'jobPosting.historyScore': 'score',
  'jobPosting.historyStatus.analyzed': 'analyzed',
  'jobPosting.historyStatus.draft-generated': 'draft generated',
  'jobPosting.historyStatus.pdf-downloaded': 'PDF downloaded',
  'jobPosting.newAnalysis': 'Analyze another Job Posting',
  'jobPosting.outgoingLabel': 'Exact Job Posting content sent for extraction',
  'jobPosting.save': 'Save minimized Job Posting',
  'jobPosting.noticeTitle': 'Job Posting processing notice',
  'jobPosting.noticeText': 'Only the Job Posting content shown above is sent to OpenAI in a stateless request with storage disabled. Standard abuse-monitoring retention may still apply.',
  'jobPosting.noticeVersion': 'Notice version:',
  'jobPosting.confirm': 'Confirm Job Posting processing',
  'jobPosting.confirmed': 'Job Posting processing confirmed for this session.',
  'jobPosting.extract': 'Extract Job Requirements',
  'jobPosting.requirementsTitle': 'Review extracted Job Requirements',
  'jobPosting.requiredShort': 'required',
  'jobPosting.preferredShort': 'preferred',
  'jobPosting.requirementGroup': 'Requirement group',
  'jobPosting.targetRoleTitle': 'Target role',
  'jobPosting.targetRoleFallbackShort': 'Untitled role',
  'jobPosting.targetRoleFallback': 'No unambiguous target role was found. The resume will use the localized fallback title.',
  'jobPosting.targetRoleEdit': 'Correct the Target Role with exact text from the Job Posting',
  'jobPosting.targetRoleSave': 'Save Target Role and refresh analysis',
  'jobPosting.classification.required': 'Required',
  'jobPosting.classification.preferred': 'Preferred',
  'jobPosting.sourceExcerpt': 'Source excerpt: ',
  'jobPosting.extractionFailure': 'Job Requirements could not be extracted. Review the content and try again.',
  'jobPosting.transportFailure': 'The extraction service could not be reached. Your Job Posting is still available; try again.',
  'jobPosting.failure': 'The Job Posting action failed. Review the content and try again.',
  'matchAnalysis.title': 'Match Score and Gap Analysis',
  'matchAnalysis.action': 'Analyze the match',
  'matchAnalysis.score': 'Match Score',
  'matchAnalysis.summaryTitle': 'Match Analysis summary',
  'matchAnalysis.band.strong': 'Strong evidence coverage',
  'matchAnalysis.band.credible': 'Credible evidence coverage',
  'matchAnalysis.band.ambitious': 'Ambitious evidence coverage',
  'matchAnalysis.coverage.covered': 'Covered',
  'matchAnalysis.coverage.partial': 'Partially covered',
  'matchAnalysis.coverage.uncovered': 'Uncovered',
  'matchAnalysis.partialShort': 'partial',
  'matchAnalysis.showDetails': 'Show every requirement and its evidence',
  'matchAnalysis.eligibleLabel': 'Generation eligibility: eligible',
  'matchAnalysis.deniedLabel': 'Generation eligibility: not eligible',
  'matchAnalysis.requiredCoverage': 'Required Job Requirements covered',
  'matchAnalysis.preferredCoverage': 'Preferred Job Requirements covered',
  'matchAnalysis.lowScoreWarning': 'Your Match Score is below 50%. This describes ambitious evidence coverage, not hiring probability, and does not block generation.',
  'matchAnalysis.eligible': 'Your relevant Candidate Facts can support an honest Tailored Resume.',
  'matchAnalysis.denied': 'No relevant Candidate Fact supports this Job Posting yet.',
  'matchAnalysis.evidenceTitle': 'Job Requirements and Match Evidence',
  'matchAnalysis.evidenceNone': 'No Job Requirement is supported by a Candidate Fact yet.',
  'matchAnalysis.gapTitle': 'Top gaps',
  'matchAnalysis.gapNone': 'Every required Job Requirement is covered.',
  'matchAnalysis.strengthTitle': 'Top strengths',
  'matchAnalysis.strengthNone': 'No fully covered professional requirement yet.',
  'matchAnalysis.practicalConstraints': 'Practical Constraints',
  'matchAnalysis.practicalConstraintsNone': 'No explicit Practical Constraint found.',
  'matchAnalysis.improvementTitle': 'Improvement Opportunities',
  'matchAnalysis.improvementNone': 'No unscored Improvement Opportunity found.',
  'matchAnalysis.enrichmentTitle': 'Optional profile enrichment',
  'matchAnalysis.enrichmentDescription': 'Add only real professional experience missing from your Source Profile. The three highest-impact required gaps are shown first.',
  'matchAnalysis.enrichmentQuestion': 'Do you have real professional experience that supports this required Job Requirement?',
  'matchAnalysis.enrichmentAnswer': 'Describe only what you actually did',
  'matchAnalysis.enrichmentKind': 'Candidate Fact type',
  'matchAnalysis.enrichmentAdd': 'Add this Candidate Fact and refresh analysis',
  'matchAnalysis.enrichmentSkip': 'Skip this question',
  'matchAnalysis.enrichmentDuplicateFailure': 'This Candidate Fact is already in your Source Profile. Your previous Match Analysis is unchanged.',
  'matchAnalysis.enrichmentInvalidFailure': 'Add a non-empty Candidate Fact or skip this question. Your previous Match Analysis is unchanged.',
  'matchAnalysis.failure': 'The Match Analysis could not be produced. Review your verified facts and try again.',
  'matchAnalysis.transportFailure': 'The matching service could not be reached. Your verified facts and Job Requirements are still available.',
  'resumeClaims.title': 'Curate your Tailored Resume claims',
  'resumeClaims.collectionTitle': 'Retained Resume Claims',
  'resumeClaims.claimLabel': 'Resume Claim',
  'resumeClaims.flowNavigation': 'Tailored Resume curation',
  'resumeClaims.description': 'Generate concise claims from your Match Evidence and Candidate Facts. Every semantic segment is checked before it is kept.',
  'resumeClaims.generate': 'Generate Resume Claims',
  'resumeClaims.regenerate': 'Regenerate Resume Claims',
  'resumeClaims.languageLegend': 'Resume language',
  'resumeClaims.excluded': 'Content that remained unsupported after one isolated rewrite was excluded from your Tailored Resume.',
  'resumeClaims.empty': 'No supported Resume Claim remains. Add and confirm professional information through your Source Profile before trying again.',
  'resumeClaims.moveUp': 'Move up',
  'resumeClaims.moveDown': 'Move down',
  'resumeClaims.remove': 'Remove claim',
  'resumeClaims.reformulationLabel': 'Request a wording change',
  'resumeClaims.reformulate': 'Request reformulation',
  'resumeClaims.editingNote': 'You can edit wording directly. New professional content must be confirmed as a Candidate Fact before it can be used.',
  'resumeClaims.edit': 'Edit claim',
  'resumeClaims.saveEdit': 'Save edit',
  'resumeClaims.confirmNewFact': 'This edit adds professional content that existing Candidate Facts do not support.',
  'resumeClaims.factKind': 'Candidate Fact type',
  'resumeClaims.confirmAndSave': 'Confirm as a new Candidate Fact',
  'resumeClaims.discardEdit': 'Discard this edit',
  'resumeClaims.unsupportedEditBlocksExport': 'Confirm or discard the unsupported edit before previewing or exporting this resume.',
  'resumeClaims.failure': 'The Resume Claims action failed. Your verified facts remain available; review them and try again.',
  'resumePreview.title': 'Preview and export',
  'resumePreview.photoSection': 'Photo',
  'resumePreview.outcomeSection': 'Outcome Feedback',
  'resumePreview.exportSection': 'PDF export',
  'resumePreview.description': 'Review the exact semantic document used for the validated A4 PDF.',
  'resumePreview.preparing': 'Preparing the exact PDF layout…',
  'resumePreview.frameTitle': 'Tailored Resume preview',
  'resumePreview.reduced': 'Lower-priority detail was omitted to preserve a truthful, readable resume.',
  'resumePreview.invalid': 'A truthful resume preview could not be prepared from the retained claims.',
  'resumePreview.photoLabel': 'Optional Candidate photo',
  'resumePreview.photoInclude': 'Include this photo in the preview and PDF',
  'resumePreview.photoPrivacy': 'The photo is disabled by default, kept separately from your Source Profile, and never sent to the writing model.',
  'resumePreview.photoFailure': 'Choose a JPEG, PNG, or WebP image smaller than 2 MB.',
  'resumePreview.download': 'Download validated A4 PDF',
  'resumePreview.usefulnessQuestion': 'Was this resume useful for your application?',
  'resumePreview.yes': 'Yes',
  'resumePreview.no': 'No',
  'resumePreview.commentLabel': 'Optional comment',
  'resumePreview.feedbackSubmit': 'Send feedback',
  'resumePreview.feedbackRecorded': 'Thanks — your feedback was recorded.',
  'resumePreview.exporting': 'Validating PDF…',
  'resumePreview.downloaded': 'The validated PDF is ready on your device.',
  'resumePreview.controlNotice': 'After download, this PDF is under your control. Store and share it only where you choose.',
  'resumePreview.overflowFailure': 'The retained content does not fit two readable A4 pages. Remove a claim or the optional photo and try again.',
  'resumePreview.contentFailure': 'PDF validation found missing or reordered retained content. Nothing was downloaded.',
  'resumePreview.fontFailure': 'The expected fonts could not be embedded. Nothing was downloaded.',
  'resumePreview.pageFailure': 'The export was not the expected one or two A4 pages. Nothing was downloaded.',
  'resumePreview.requestFailure': 'The resume export request was invalid. Review the preview and try again.',
  'resumePreview.provenanceFailure': 'A retained claim is no longer linked to a Verified Fact. Nothing was downloaded.',
  'resumePreview.validationFailure': 'The claim validation service is unavailable. Nothing was downloaded; try again later.',
  'resumePreview.renderFailure': 'The PDF renderer is unavailable. Your preview and verified facts remain in this browser.',
  'operation.analyzeMatch': 'Building your Match Analysis…',
  'operation.extractJobRequirements': 'Extracting Job Requirements…',
  'operation.extractSourceProfile': 'Extracting professional facts…',
  'operation.editResumeClaim': 'Checking your Resume Claim edit…',
  'operation.generateResumeClaims': 'Drafting your Tailored Resume…',
  'operation.importSourceDocument': 'Reading your Source Document…',
  'operation.reformulateResumeClaim': 'Reformulating your Resume Claim…',
  'operation.retry': 'Retry operation',
  'operation.retryJobPosting': 'Retry Job Posting',
  'operation.retryMatchAnalysis': 'Retry Match Analysis',
  'operation.retrySourceProfile': 'Retry Source Profile',
  'operation.retryTailoredResume': 'Retry Tailored Resume',
  'operation.stillWorking': 'Still working. Your content is safe in this browser.',
  'privacy.retention': 'Candidate content you add stays in this browser and expires locally after 24 hours. Downloaded files remain on your device and are outside this automatic expiration.',
  'workflow.title': 'Your workflow',
  'workflow.opened': 'Workflow opened',
  'workflow.openedDescription': 'Your Source Profile is the next step.',
  'workflow.ready': 'Ready to begin',
  'workflow.readyDescription': 'Click “Start tailoring” to begin your workflow.',
  'workflow.sourceProfile': 'Source Profile',
  'workflow.sourceProfileDescription': 'Use your existing resume or career details as the source of truth.',
  'workflow.jobPosting': 'Job Posting',
  'workflow.jobPostingDescription': 'Add the Job Posting you are targeting so we can identify what to highlight.',
  'workflow.matchAnalysis': 'Match Analysis',
  'workflow.matchAnalysisDescription': 'Review evidence, coverage, and gaps before generating your resume.',
  'workflow.tailoredResume': 'Tailored Resume',
  'workflow.tailoredResumeDescription': 'Review a focused resume based only on your approved facts.',
  'workflow.progressLabel': 'Resume Tailoring progress',
  'workflow.completed': 'Completed',
  'workflow.current': 'Current',
  'workflow.unavailable': 'Not available yet',
  'workflow.verifiedFacts': 'verified fact',
  'workflow.requirements': 'Job Requirements',
  'workflow.matchScore': 'Match Score',
  'workflow.resumeClaims': 'Resume Claims ready',
  'value.controlTitle': 'You stay in control',
  'value.controlText': 'Only use information you have reviewed and approved.',
  'value.focusTitle': 'A more focused story',
  'value.focusText': 'Show the most relevant version of your experience.',
  'value.opportunitiesTitle': 'Built for real opportunities',
  'value.opportunitiesText': 'Tailor with confidence, apply with integrity.',
  'notFound.title': 'Page not found',
  'notFound.description': 'The page you requested does not belong to this Resume Tailoring workflow.',
  'notFound.return': 'Return to the workflow',
} as const

type TranslationKey = keyof typeof englishCatalog
type TranslationCatalog = Readonly<Record<TranslationKey, string>>

const frenchCatalog = {
  'brand.homeLabel': "Accueil d'Honest Resume",
  'brand.name': 'Honest Resume',
  'brand.tagline': 'Une manière plus honnête de décrocher un emploi.',
  'demoAccess.title': 'Préparation de la démo',
  'demoAccess.description': "Une vérification rapide protège cette démo publique contre les abus automatisés. Aucun compte n'est nécessaire.",
  'demoAccess.verifying': "Vérification de l'accès…",
  'demoAccess.retry': 'Relancer la vérification de sécurité',
  'locale.english': 'Anglais',
  'locale.french': 'Français',
  'locale.persistenceFailure': "On n'a pas pu enregistrer ta préférence de langue.",
  'locale.unavailable': "La langue de l'interface n'est pas disponible.",
  'locale.switcherLabel': 'Langue',
  'hero.title': 'Adapte ton CV sans rien inventer.',
  'hero.lede': 'Crée un CV ciblé à partir des informations que tu as vérifiées et approuvées.',
  'candidateJourney.eyebrow': 'Parcours Candidat',
  'candidateJourney.title': "Un CV honnête, adapté à l'opportunité.",
  'candidateJourney.description': 'Garde tes preuves professionnelles dans ce navigateur pendant une Session Candidat de 24 heures et avance à travers trois phases ciblées.',
  'candidateJourney.privateByDesign': 'Privé par conception',
  'candidateJourney.phasesLabel': 'Phases du Parcours Candidat',
  'candidateJourney.sourceIntake': 'Collecte des Sources',
  'candidateJourney.sourceIntakeDescription': 'Ajoute les faits professionnels qui peuvent soutenir ta candidature.',
  'candidateJourney.jobMatch': "Correspondance avec l'Offre",
  'candidateJourney.jobMatchDescription': "Compare tes preuves à une Offre d'emploi.",
  'candidateJourney.tailoredResumePreparation': 'Préparation du CV Adapté',
  'candidateJourney.tailoredResumePreparationDescription': 'Prépare et exporte un CV fondé sur tes preuves.',
  'tailoredResume.ready': 'CV adapté prêt',
  'tailoredResume.fallbackRole': 'CV adapté',
  'tailoredResume.valueProposition': 'Proposition de valeur',
  'tailoredResume.experiences': 'Expérience',
  'tailoredResume.chronology.relevant': 'Expérience pertinente',
  'tailoredResume.chronology.context': 'Expérience de contexte',
  'tailoredResume.chronology.earlier': 'Expérience antérieure',
  'tailoredResume.section.skills': 'Compétences',
  'tailoredResume.section.education': 'Formation',
  'tailoredResume.section.languages': 'Langues',
  'tailoredResume.section.projects': 'Projets',
  'tailoredResume.section.certifications': 'Certifications',
  'tailoredResume.language': 'Langue du CV',
  'tailoredResume.languageAutomatic': 'Langue de l’offre',
  'tailoredResume.contactDetails': 'Coordonnées locales',
  'tailoredResume.name': 'Nom',
  'tailoredResume.email': 'E-mail',
  'tailoredResume.phone': 'Téléphone',
  'tailoredResume.editFields': 'Modifier les champs du CV adapté',
  'tailoredResume.fieldLabel': 'Champ du CV',
  'tailoredResume.saveField': 'Enregistrer la formulation',
  'tailoredResume.attestField': 'Attester comme nouveau Candidate Fact',
  'tailoredResume.unsupportedField': 'Cette modification professionnelle n’est pas étayée par les Candidate Facts actuels.',
  'tailoredResume.unsupportedFields': 'Résous ou atteste chaque champ professionnel non étayé avant l’export.',
  'tailoredResume.hideField': 'Masquer le champ',
  'tailoredResume.hiddenFields': 'Champs masqués',
  'tailoredResume.restoreField': 'Restaurer le champ',
  'tailoredResume.moveUp': 'Monter',
  'tailoredResume.moveDown': 'Descendre',
  'tailoredResume.exportBlocked': 'L’export est bloqué tant qu’un champ professionnel non étayé reste à résoudre.',
  'candidateJourney.startSession': 'Démarrer une Session Candidat',
  'candidateJourney.sessionActive': 'Session Candidat active',
  'candidateJourney.deleteSession': 'Supprimer la Session Candidat',
  'candidateJourney.deleteDialogTitle': 'Supprimer la Session Candidat ?',
  'candidateJourney.deleteDialogDescription': 'Cette action supprime immédiatement la Session Candidat stockée dans ce navigateur.',
  'candidateJourney.deleteCancel': 'Annuler',
  'candidateJourney.deleteConfirm': 'Supprimer la session maintenant',
  'candidateJourney.sessionDeleted': 'Session Candidat supprimée de ce navigateur.',
  'candidateJourney.expiredSessionDiscarded': 'Ta Session Candidat expirée a été supprimée de ce navigateur.',
  'candidateJourney.incompatibleSessionDiscarded': 'Une Session Candidat incompatible a été supprimée de ce navigateur.',
  'candidateJourney.storageUnavailable': "Le stockage de la Session Candidat n'est pas disponible.",
  'processingPolicy.title': 'Politique de Traitement',
  'processingPolicy.description': "Vérifie la politique active avant l'envoi de tout contenu Candidat au traitement par modèle.",
  'processingPolicy.provider': 'Fournisseur',
  'processingPolicy.purposes': 'Finalités',
  'processingPolicy.transmittedDataCategories': 'Données envoyées',
  'processingPolicy.retentionPolicy': 'Conservation',
  'processingPolicy.storageBehavior': 'Stockage',
  'processingPolicy.version': 'Version de la politique',
  'processingPolicy.grantConsent': 'Accorder le Consentement au Traitement',
  'processingPolicy.consentGranted': 'Consentement au Traitement accordé pour cette politique.',
  'processingPolicy.purpose.extractEvidence': 'Extraire et structurer les preuves professionnelles',
  'processingPolicy.purpose.compareEvidence': "Comparer les preuves du Candidat aux exigences de l’Offre d’emploi",
  'processingPolicy.purpose.writeResume': 'Rédiger et valider le contenu étayé du CV Adapté',
  'processingPolicy.data.minimizedProfessionalContent': 'Contenu professionnel minimisé',
  'processingPolicy.data.jobPostingContent': "Contenu de l’Offre d’emploi",
  'processingPolicy.data.candidateFacts': 'Faits Candidats nécessaires à la correspondance, à la rédaction et à la validation',
  'processingPolicy.retentionValue': "Les entrées et sorties de l’API peuvent être conservées jusqu’à 30 jours pour surveiller les abus, ou plus longtemps si la loi l’exige.",
  'processingPolicy.storageValue': 'Le contenu du Candidat reste dans le navigateur ; les requêtes au modèle sont sans état et le stockage applicatif est désactivé.',
  'sourceIntake.title': 'Complète ta Collecte des Sources',
  'sourceIntake.description': 'Importe un PDF texte ou un DOCX, ou colle du texte professionnel. Tes coordonnées restent dans ce navigateur.',
  'sourceIntake.pasteMethod': 'Coller du texte',
  'sourceIntake.uploadMethod': 'Importer un PDF ou DOCX',
  'sourceIntake.professionalText': 'Texte professionnel',
  'sourceIntake.professionalTextPlaceholder': 'Colle tes expériences, projets, compétences, formations, langues et certifications',
  'sourceIntake.sourceFile': 'Document Source',
  'sourceIntake.sourceFileHint': 'Choisis un PDF ou DOCX (cinq pages maximum)',
  'sourceIntake.submit': 'Construire mon Profil Source',
  'sourceIntake.ready': 'Ton Profil Source est prêt.',
  'sourceIntake.inspectProfile': 'Inspecter le Profil Source',
  'sourceIntake.hideProfile': 'Masquer le Profil Source',
  'sourceIntake.detailedProfile': 'Profil Source détaillé',
  'sourceIntake.ambiguities': 'Résoudre les Ambiguïtés Critiques',
  'sourceIntake.answerAmbiguity': 'Enregistrer cette réponse',
  'sourceIntake.experiences': 'Expériences',
  'sourceIntake.projects': 'Projets',
  'sourceIntake.skills': 'Compétences',
  'sourceIntake.education': 'Formation',
  'sourceIntake.languages': 'Langues',
  'sourceIntake.certifications': 'Certifications',
  'sourceIntake.failure.ambiguity': "Cette Ambiguïté Critique n'est plus disponible.",
  'sourceIntake.failure.storage': "Le Profil Source n'a pas pu être enregistré dans ce navigateur.",
  'sourceIntake.failure.encrypted': 'Ce document est chiffré. Importe une copie déverrouillée ou colle son texte.',
  'sourceIntake.failure.empty': 'Ajoute du texte professionnel avant de continuer.',
  'sourceIntake.failure.invalid': 'Ce document est invalide. Exporte un nouveau PDF ou DOCX puis réessaie.',
  'sourceIntake.failure.oversized': 'Utilise un document de cinq pages et 5 Mo maximum, ou colle jusqu’à 50 000 caractères.',
  'sourceIntake.failure.consent': 'Accorde le Consentement au Traitement avant de construire le Profil Source.',
  'sourceIntake.failure.scanned': 'Ce PDF semble être un scan. Utilise un PDF avec du texte sélectionnable ou colle le texte.',
  'sourceIntake.failure.extraction': "Le Profil Source n'a pas pu être extrait. Ta Session Candidat est inchangée ; réessaie.",
  'sourceIntake.failure.unreadable': "Ce document n'a pas pu être lu. Importe une autre copie ou colle le texte.",
  'sourceIntake.failure.unsupported': 'Seuls les PDF texte, DOCX et textes collés sont pris en charge.',
  'jobMatch.title': 'Analyse une Offre d’emploi',
  'jobMatch.description': 'Colle l’offre ou importe un PDF texte ou TXT. Le bruit employeur et les répétitions ne gonflent pas le résultat.',
  'jobMatch.pasteMethod': 'Coller le texte',
  'jobMatch.uploadMethod': 'Importer un PDF ou TXT',
  'jobMatch.textLabel': 'Texte de l’Offre d’emploi',
  'jobMatch.textPlaceholder': 'Colle l’Offre d’emploi complète',
  'jobMatch.fileLabel': 'Fichier de l’Offre d’emploi',
  'jobMatch.fileHint': 'Choisis un PDF texte ou TXT',
  'jobMatch.submit': 'Analyser cette Offre d’emploi',
  'jobMatch.targetRole': 'Poste ciblé',
  'jobMatch.measurement': 'Ce score mesure la couverture des exigences professionnelles explicites par tes Faits Candidats. Ce n’est pas une probabilité d’embauche.',
  'jobMatch.strengths': 'Trois correspondances les plus fortes',
  'jobMatch.gaps': 'Trois écarts prioritaires',
  'jobMatch.criticalReserve': 'Réserve sur Exigence Critique',
  'jobMatch.criticalReserve.clear': 'Aucune exigence critique ne présente de réserve de preuve.',
  'jobMatch.criticalReserve.present': 'Une ou plusieurs exigences critiques sont partielles ou non étayées. Lis ces écarts avant de décider de postuler.',
  'jobMatch.constraints': 'Contraintes Pratiques importantes',
  'jobMatch.constraints.none': 'Aucune Contrainte Pratique explicite n’a été trouvée.',
  'jobMatch.details': 'Détails complets des exigences et preuves',
  'jobMatch.importance.critical': 'Critique',
  'jobMatch.importance.central': 'Centrale',
  'jobMatch.importance.complementary': 'Complémentaire',
  'jobMatch.coverage.covered': 'Couverte',
  'jobMatch.coverage.partially-covered': 'Partiellement couverte',
  'jobMatch.coverage.uncovered': 'Non couverte',
  'jobMatch.sourceExcerpt': 'Extrait source exact',
  'jobMatch.evidence': 'Preuve du Candidat',
  'jobMatch.evidence.none': 'Aucun Fait Candidat ne l’étaye.',
  'jobMatch.failure.empty': 'Ajoute le texte de l’Offre d’emploi avant de continuer.',
  'jobMatch.failure.invalid': 'Ce fichier d’Offre d’emploi est invalide.',
  'jobMatch.failure.oversized': 'Utilise une Offre d’emploi de moins de 5 Mo et 100 000 caractères.',
  'jobMatch.failure.scanned': 'Ce PDF semble scanné. Utilise un PDF avec du texte sélectionnable ou colle le texte.',
  'jobMatch.failure.unsupported': 'Seuls le texte collé, les PDF texte et les fichiers TXT sont pris en charge. L’extraction depuis une URL n’est pas disponible.',
  'jobMatch.failure.unreadable': 'Cette Offre d’emploi est illisible. Importe une autre copie ou colle le texte.',
  'jobMatch.failure.extraction': 'L’Offre d’emploi n’a pas pu être analysée. Le dernier résultat stable reste disponible ; réessaie.',
  'jobMatch.failure.evidence': 'Les Preuves de Correspondance n’ont pas pu être validées. Le dernier résultat stable reste disponible ; réessaie.',
  'jobMatch.failure.consent': 'Accorde le Consentement au Traitement avant d’analyser une Offre d’emploi.',
  'jobMatch.failure.storage': 'L’Analyse de Correspondance n’a pas pu être enregistrée dans ce navigateur.',
  'jobMatch.enrichmentUnavailable': 'Cette exigence ne peut pas recevoir un Enrichissement du Profil.',
  'jobMatch.generation.denied': 'Aucun Fait Candidat pertinent ne permet de produire honnêtement un CV Adapté.',
  'jobMatch.generation.eligible': 'Tes preuves permettent de produire honnêtement un CV Adapté.',
  'jobMatch.generation.lowScoreWarning': 'Un Score de Correspondance faible est un avertissement, pas un blocage de génération.',
  'jobMatch.generation.normalizedAction': 'Utiliser mon CV source normalisé — non adapté',
  'jobMatch.generation.normalizedNotice': 'Seule une version normalisée de ton Profil Source est disponible. Elle ne prétendra pas être adaptée à l’Offre d’emploi.',
  'jobMatch.generation.tailoredAction': 'Préparer mon CV Adapté',
  'jobMatch.generation.normalizedDocumentTitle': 'CV SOURCE NORMALISÉ — NON ADAPTÉ',
  'jobMatch.generation.normalizedContact': 'COORDONNÉES',
  'jobMatch.generation.normalizedExperience': 'EXPÉRIENCE',
  'jobMatch.generation.normalizedExperienceFallback': 'Expérience',
  'jobMatch.generation.normalizedProjects': 'PROJETS',
  'jobMatch.generation.normalizedSkills': 'COMPÉTENCES',
  'jobMatch.generation.normalizedEducation': 'FORMATION',
  'jobMatch.generation.normalizedLanguages': 'LANGUES',
  'jobMatch.generation.normalizedCertifications': 'CERTIFICATIONS',
  'jobMatch.generation.normalizedAdditional': 'INFORMATIONS VÉRIFIÉES SUPPLÉMENTAIRES',
  'jobMatch.generation.normalizedFileName': 'cv-source-normalise-non-adapte.txt',
  'jobMatch.generation.contact.address': 'Adresse',
  'jobMatch.generation.contact.date-of-birth': 'Date de naissance',
  'jobMatch.generation.contact.email': 'E-mail',
  'jobMatch.generation.contact.personal-information': 'Informations personnelles',
  'jobMatch.generation.contact.phone': 'Téléphone',
  'jobMatch.generation.contact.url': 'URL',
  'session.start': "Commencer à adapter mon CV",
  'session.delete': 'Supprimer ma session privée',
  'session.controlsLabel': 'Contrôles de la session privée',
  'session.deleteDialogTitle': 'Supprimer ma session privée ?',
  'session.deleteDialogDescription': 'Cette action supprime immédiatement cette session Candidat de ce navigateur et l’invalide dans tous les onglets ouverts.',
  'session.deleteContentIntro': 'Lorsqu’ils sont présents, les contenus locaux au navigateur supprimés comprennent :',
  'session.deleteSourceDocument': 'Document Source',
  'session.deleteSourceProfile': 'Profil Source',
  'session.deleteJobPosting': "Offre d'emploi",
  'session.deleteMatchAnalysis': 'Analyse de Correspondance',
  'session.deleteTailoredResume': 'CV Adapté',
  'session.deletePhoto': 'Photo fournie par le Candidat',
  'session.deleteCancel': 'Annuler',
  'session.deleteConfirm': 'Supprimer la session maintenant',
  'session.loadFailure': "On n'a pas pu charger ta session privée.",
  'session.openFailure': "On n'a pas pu ouvrir ton parcours. Réessaie.",
  'session.deleteFailure': "On n'a pas pu supprimer ta session privée. Réessaie.",
  'sourceProfile.title': 'Construis ton Profil Source',
  'sourceProfile.importDescription': 'Ton CV est la source de vérité. Relis le profil compact et corrige uniquement ce qui doit changer.',
  'sourceProfile.methodLabel': 'Méthode du Document Source',
  'sourceProfile.pdfMethod': 'PDF texte',
  'sourceProfile.pdfDescription': "Utilise un CV existant ou un PDF LinkedIn avec du texte sélectionnable. Les PDF scannés composés uniquement d'images ne peuvent pas être lus.",
  'sourceProfile.choosePdf': 'Choisir un PDF',
  'sourceProfile.noFileSelected': 'Aucun PDF sélectionné',
  'sourceProfile.selectedFile': 'PDF sélectionné :',
  'sourceProfile.textMethod': 'Coller du texte professionnel',
  'sourceProfile.textDescription': 'Colle tes expériences professionnelles, formations, compétences, langues ou projets.',
  'sourceProfile.textLabel': 'Texte professionnel',
  'sourceProfile.textPlaceholder': 'Colle tes informations professionnelles ici',
  'sourceProfile.reviewText': 'Vérifier le texte collé',
  'sourceProfile.emptyTextFailure': 'Colle du texte professionnel avant de continuer.',
  'sourceProfile.reviewSurfaceTitle': 'Vérifie le Document Source sortant',
  'sourceProfile.detectedTitle': 'Retiré avant le traitement',
  'sourceProfile.detectedNone': "Aucune coordonnée ni information personnelle sensible courante n'a été détectée.",
  'sourceProfile.sensitiveKind.email': 'Adresse e-mail',
  'sourceProfile.sensitiveKind.phone': 'Numéro de téléphone',
  'sourceProfile.sensitiveKind.url': 'Adresse web',
  'sourceProfile.sensitiveKind.address': 'Adresse postale',
  'sourceProfile.sensitiveKind.date-of-birth': 'Date de naissance',
  'sourceProfile.sensitiveKind.personal-information': 'Information personnelle',
  'sourceProfile.outgoingLabel': "Contenu exact envoyé pour l'extraction",
  'sourceProfile.saveContent': 'Enregistrer le contenu minimisé',
  'sourceProfile.noticeTitle': 'Notice de traitement',
  'sourceProfile.noticeText': "OpenAI reçoit le contenu professionnel minimisé affiché ci-dessus, le contenu ultérieur des Offres d'emploi et les Faits Candidats nécessaires à l'analyse et à la rédaction au moyen de requêtes sans état avec le stockage désactivé. La conservation standard liée à la surveillance des abus peut tout de même s'appliquer. Ce consentement couvre les opérations du modèle pendant cette Session Candidat de 24 heures tant que la version de la notice reste à jour.",
  'sourceProfile.noticeVersion': 'Version de la notice :',
  'sourceProfile.confirmNotice': 'Confirmer cette notice de traitement',
  'sourceProfile.confirmAndExtract': 'Continuer et analyser mon CV',
  'sourceProfile.noticeConfirmed': 'Notice de traitement confirmée pour cette session.',
  'sourceProfile.extract': 'Extraire les faits professionnels',
  'sourceProfile.factsTitle': 'Vérifie ton profil importé',
  'sourceProfile.reviewProgress': 'Faits vérifiés :',
  'sourceProfile.filterLabel': 'Filtrer les faits par statut',
  'sourceProfile.filterAll': 'Tous',
  'sourceProfile.filterEmpty': 'Aucun fait ne correspond à ce filtre.',
  'sourceProfile.showMore': 'Afficher plus de faits',
  'sourceProfile.batchTitle': 'Faits sélectionnés pour la confirmation groupée',
  'sourceProfile.batchDescription': 'Vérifie chaque fait de cette liste visible avant de confirmer le lot.',
  'sourceProfile.batchConfirm': 'Confirmer',
  'sourceProfile.conflictsTitle': 'Conflits à résoudre',
  'sourceProfile.conflictsDescription': 'Conserve explicitement une proposition ou rejette un fait contradictoire.',
  'sourceProfile.conflictsAnnouncement': 'faits contradictoires à résoudre.',
  'sourceProfile.factStates': 'États des faits :',
  'sourceProfile.select': 'Sélectionner',
  'sourceProfile.selectFact': 'Sélectionner',
  'sourceProfile.selectGroup': 'Sélectionner les faits visibles de ce groupe',
  'sourceProfile.selectedFact': 'fait sélectionné',
  'sourceProfile.selectedFacts': 'faits sélectionnés',
  'sourceProfile.confirmFact': 'Confirmer le fait',
  'sourceProfile.rejectFact': 'Rejeter le fait',
  'sourceProfile.correctFact': 'Créer la correction',
  'sourceProfile.correctionLabel': 'Corriger cette information',
  'sourceProfile.resolveConflict': 'Garder ce fait et résoudre le conflit',
  'sourceProfile.unsupportedFailure': "Choisis un fichier PDF. Les autres formats de Document Source ne sont pas encore pris en charge.",
  'sourceProfile.encryptedPdfFailure': "Ce PDF est protégé par un mot de passe. Déverrouille-le ou exporte une copie non protégée, puis réessaie.",
  'sourceProfile.invalidPdfFailure': "Ce fichier n'est pas un PDF valide. Choisis un autre fichier PDF.",
  'sourceProfile.textEmptyPdfFailure': "Ce PDF ne contient aucun texte sélectionnable. Utilise un PDF texte ou colle plutôt ton texte professionnel.",
  'sourceProfile.unreadableFailure': "Ce PDF n'a pas pu être lu entièrement. Choisis un autre PDF texte et réessaie.",
  'sourceProfile.browserCompatibilityFailure': "Ce navigateur ne peut pas lire les PDF de manière fiable. Mets à jour Safari, Chrome ou Firefox, ou colle plutôt ton texte professionnel.",
  'sourceProfile.extractionFailure': "Les faits professionnels n'ont pas pu être extraits. Vérifie la configuration du service et réessaie.",
  'sourceProfile.failure': "L'action sur le Profil Source a échoué. Vérifie le PDF ou la configuration et réessaie.",
  'sourceProfile.kind.experience': 'Expérience',
  'sourceProfile.kind.skill': 'Compétence',
  'sourceProfile.kind.education': 'Formation',
  'sourceProfile.kind.certification': 'Certification',
  'sourceProfile.kind.language': 'Langue',
  'sourceProfile.kind.project': 'Projet',
  'sourceProfile.status.extracted': 'À vérifier',
  'sourceProfile.status.verified': 'Issu de ton CV',
  'sourceProfile.status.rejected': 'Rejeté',
  'sourceProfile.status.superseded': 'Remplacé',
  'jobPosting.title': "Vérifie ton Offre d'emploi",
  'jobPosting.inputLabel': "Colle l'Offre d'emploi",
  'jobPosting.fileLabel': "Ou importe l'Offre d'emploi au format PDF ou TXT",
  'jobPosting.analyze': "Analyser cette Offre d'emploi",
  'jobPosting.review': "Vérifier cette Offre d'emploi",
  'jobPosting.historyTitle': 'Offres déjà analysées',
  'jobPosting.historyScore': 'score',
  'jobPosting.historyStatus.analyzed': 'analysée',
  'jobPosting.historyStatus.draft-generated': 'brouillon généré',
  'jobPosting.historyStatus.pdf-downloaded': 'PDF téléchargé',
  'jobPosting.newAnalysis': 'Analyser une autre Offre d’emploi',
  'jobPosting.outgoingLabel': "Contenu exact de l'Offre d'emploi envoyé pour l'extraction",
  'jobPosting.save': "Enregistrer l'Offre d'emploi minimisée",
  'jobPosting.noticeTitle': "Notice de traitement de l'Offre d'emploi",
  'jobPosting.noticeText': "Seul le contenu de l'Offre d'emploi affiché ci-dessus est envoyé à OpenAI dans une requête sans état avec le stockage désactivé. La conservation standard liée à la surveillance des abus peut tout de même s'appliquer.",
  'jobPosting.noticeVersion': 'Version de la notice :',
  'jobPosting.confirm': "Confirmer le traitement de l'Offre d'emploi",
  'jobPosting.confirmed': "Traitement de l'Offre d'emploi confirmé pour cette session.",
  'jobPosting.extract': "Extraire les Exigences de l'Offre",
  'jobPosting.requirementsTitle': "Vérifie les Exigences de l'Offre extraites",
  'jobPosting.requiredShort': 'obligatoires',
  'jobPosting.preferredShort': 'souhaitées',
  'jobPosting.requirementGroup': "Groupe d'exigences",
  'jobPosting.targetRoleTitle': 'Poste ciblé',
  'jobPosting.targetRoleFallbackShort': 'Poste sans titre',
  'jobPosting.targetRoleFallback': "Aucun poste ciblé non ambigu n'a été trouvé. Le CV utilisera le titre localisé par défaut.",
  'jobPosting.targetRoleEdit': "Corrige le Poste ciblé avec le texte exact de l'Offre d'emploi",
  'jobPosting.targetRoleSave': "Enregistrer le Poste ciblé et actualiser l'analyse",
  'jobPosting.classification.required': 'Obligatoire',
  'jobPosting.classification.preferred': 'Souhaitée',
  'jobPosting.sourceExcerpt': 'Extrait source : ',
  'jobPosting.extractionFailure': "Les Exigences de l'Offre n'ont pas pu être extraites. Vérifie le contenu et réessaie.",
  'jobPosting.transportFailure': "Le service d'extraction est inaccessible. Ton Offre d'emploi est toujours disponible ; réessaie.",
  'jobPosting.failure': "L'action sur l'Offre d'emploi a échoué. Vérifie le contenu et réessaie.",
  'matchAnalysis.title': 'Score de Correspondance et Analyse des Écarts',
  'matchAnalysis.action': 'Analyser la correspondance',
  'matchAnalysis.score': 'Score de Correspondance',
  'matchAnalysis.summaryTitle': 'Résumé de l’Analyse de Correspondance',
  'matchAnalysis.band.strong': 'Couverture de preuves forte',
  'matchAnalysis.band.credible': 'Couverture de preuves crédible',
  'matchAnalysis.band.ambitious': 'Couverture de preuves ambitieuse',
  'matchAnalysis.coverage.covered': 'Couverte',
  'matchAnalysis.coverage.partial': 'Partiellement couverte',
  'matchAnalysis.coverage.uncovered': 'Non couverte',
  'matchAnalysis.partialShort': 'partielle',
  'matchAnalysis.showDetails': 'Afficher toutes les exigences et leurs preuves',
  'matchAnalysis.eligibleLabel': 'Éligibilité à la génération : autorisée',
  'matchAnalysis.deniedLabel': 'Éligibilité à la génération : non autorisée',
  'matchAnalysis.requiredCoverage': "Exigences obligatoires de l’Offre couvertes",
  'matchAnalysis.preferredCoverage': "Exigences souhaitées de l’Offre couvertes",
  'matchAnalysis.lowScoreWarning': "Ton Score de Correspondance est inférieur à 50 %. Il décrit une couverture de preuves ambitieuse, pas une probabilité d'embauche, et ne bloque pas la génération.",
  'matchAnalysis.eligible': 'Tes Faits Candidats pertinents peuvent soutenir un CV Adapté honnête.',
  'matchAnalysis.denied': "Aucun Fait Candidat pertinent ne soutient encore cette Offre d'emploi.",
  'matchAnalysis.evidenceTitle': "Exigences de l'Offre et Preuves de Correspondance",
  'matchAnalysis.evidenceNone': "Aucune Exigence de l'Offre n'est encore soutenue par un Fait Candidat.",
  'matchAnalysis.gapTitle': 'Principaux écarts',
  'matchAnalysis.gapNone': "Toutes les Exigences obligatoires de l'Offre sont couvertes.",
  'matchAnalysis.strengthTitle': 'Trois forces principales',
  'matchAnalysis.strengthNone': "Aucune exigence professionnelle n'est encore entièrement couverte.",
  'matchAnalysis.practicalConstraints': 'Contraintes Pratiques',
  'matchAnalysis.practicalConstraintsNone': "Aucune Contrainte Pratique explicite n'a été trouvée.",
  'matchAnalysis.improvementTitle': "Opportunités d'Amélioration",
  'matchAnalysis.improvementNone': "Aucune Opportunité d'Amélioration non scorée n'a été trouvée.",
  'matchAnalysis.enrichmentTitle': 'Enrichissement facultatif du Profil Source',
  'matchAnalysis.enrichmentDescription': "Ajoute uniquement une expérience professionnelle réelle absente de ton Profil Source. Les trois écarts obligatoires au plus fort impact sont affichés en premier.",
  'matchAnalysis.enrichmentQuestion': "As-tu une expérience professionnelle réelle qui appuie cette Exigence de l'Offre obligatoire ?",
  'matchAnalysis.enrichmentAnswer': 'Décris uniquement ce que tu as réellement fait',
  'matchAnalysis.enrichmentKind': 'Type de Fait Candidat',
  'matchAnalysis.enrichmentAdd': "Ajouter ce Fait Candidat et actualiser l'analyse",
  'matchAnalysis.enrichmentSkip': 'Ignorer cette question',
  'matchAnalysis.enrichmentDuplicateFailure': "Ce Fait Candidat figure déjà dans ton Profil Source. Ton Analyse de Correspondance précédente est conservée.",
  'matchAnalysis.enrichmentInvalidFailure': "Ajoute un Fait Candidat non vide ou ignore cette question. Ton Analyse de Correspondance précédente est conservée.",
  'matchAnalysis.failure': "L'Analyse de Correspondance n'a pas pu être produite. Vérifie tes faits confirmés et réessaie.",
  'matchAnalysis.transportFailure': 'Le service de correspondance est inaccessible. Tes faits vérifiés et les Exigences de l’Offre sont toujours disponibles.',
  'resumeClaims.title': 'Compose les affirmations de ton CV Adapté',
  'resumeClaims.collectionTitle': 'Affirmations du CV conservées',
  'resumeClaims.claimLabel': 'Affirmation du CV',
  'resumeClaims.flowNavigation': 'Composition du CV Adapté',
  'resumeClaims.description': 'Génère des affirmations concises à partir de tes Preuves de Correspondance et Faits Candidats. Chaque segment sémantique est contrôlé avant d’être conservé.',
  'resumeClaims.generate': 'Générer les affirmations du CV',
  'resumeClaims.regenerate': 'Régénérer les affirmations du CV',
  'resumeClaims.languageLegend': 'Langue du CV',
  'resumeClaims.excluded': 'Le contenu resté non étayé après une reformulation isolée a été exclu de ton CV Adapté.',
  'resumeClaims.empty': 'Aucune affirmation étayée ne reste. Ajoute et confirme les nouvelles informations professionnelles dans ton Profil Source avant de réessayer.',
  'resumeClaims.moveUp': 'Monter',
  'resumeClaims.moveDown': 'Descendre',
  'resumeClaims.remove': 'Supprimer l’affirmation',
  'resumeClaims.reformulationLabel': 'Demander un changement de formulation',
  'resumeClaims.reformulate': 'Demander la reformulation',
  'resumeClaims.editingNote': 'Tu peux modifier directement la formulation. Tout nouveau contenu professionnel doit être confirmé comme Fait Candidat avant d’être utilisé.',
  'resumeClaims.edit': 'Modifier l’affirmation',
  'resumeClaims.saveEdit': 'Enregistrer la modification',
  'resumeClaims.confirmNewFact': 'Cette modification ajoute du contenu professionnel non étayé par les Faits Candidats existants.',
  'resumeClaims.factKind': 'Type de Fait Candidat',
  'resumeClaims.confirmAndSave': 'Confirmer comme nouveau Fait Candidat',
  'resumeClaims.discardEdit': 'Abandonner cette modification',
  'resumeClaims.unsupportedEditBlocksExport': 'Confirme ou abandonne la modification non étayée avant de prévisualiser ou d’exporter ce CV.',
  'resumeClaims.failure': 'L’action sur les affirmations du CV a échoué. Tes faits vérifiés restent disponibles ; vérifie-les et réessaie.',
  'resumePreview.title': 'Aperçu et export',
  'resumePreview.photoSection': 'Photo',
  'resumePreview.outcomeSection': 'Retour sur le résultat',
  'resumePreview.exportSection': 'Export PDF',
  'resumePreview.description': 'Relis le document sémantique exact utilisé pour le PDF A4 validé.',
  'resumePreview.preparing': 'Préparation de la mise en page exacte du PDF…',
  'resumePreview.frameTitle': 'Aperçu du CV Adapté',
  'resumePreview.reduced': 'Les détails moins prioritaires ont été omis pour préserver un CV honnête et lisible.',
  'resumePreview.invalid': 'Impossible de préparer un aperçu honnête à partir des affirmations conservées.',
  'resumePreview.photoLabel': 'Photo facultative du Candidat',
  'resumePreview.photoInclude': 'Inclure cette photo dans l’aperçu et le PDF',
  'resumePreview.photoPrivacy': 'La photo est désactivée par défaut, conservée séparément du Profil Source et jamais envoyée au modèle de rédaction.',
  'resumePreview.photoFailure': 'Choisis une image JPEG, PNG ou WebP de moins de 2 Mo.',
  'resumePreview.download': 'Télécharger le PDF A4 validé',
  'resumePreview.usefulnessQuestion': 'Ce CV était-il utile pour ta candidature ?',
  'resumePreview.yes': 'Oui',
  'resumePreview.no': 'Non',
  'resumePreview.commentLabel': 'Commentaire facultatif',
  'resumePreview.feedbackSubmit': 'Envoyer le retour',
  'resumePreview.feedbackRecorded': 'Merci — ton retour a été enregistré.',
  'resumePreview.exporting': 'Validation du PDF…',
  'resumePreview.downloaded': 'Le PDF validé est prêt sur ton appareil.',
  'resumePreview.controlNotice': 'Après le téléchargement, ce PDF est sous ton contrôle. Conserve-le et partage-le uniquement où tu le décides.',
  'resumePreview.overflowFailure': 'Le contenu conservé ne tient pas sur deux pages A4 lisibles. Supprime une affirmation ou la photo facultative puis réessaie.',
  'resumePreview.contentFailure': 'La validation du PDF a trouvé du contenu conservé manquant ou réordonné. Aucun fichier n’a été téléchargé.',
  'resumePreview.fontFailure': 'Les polices attendues n’ont pas pu être incorporées. Aucun fichier n’a été téléchargé.',
  'resumePreview.pageFailure': 'L’export ne comporte pas le nombre attendu d’une ou deux pages A4. Aucun fichier n’a été téléchargé.',
  'resumePreview.requestFailure': 'La demande d’export du CV est invalide. Vérifie l’aperçu puis réessaie.',
  'resumePreview.provenanceFailure': 'Une affirmation conservée n’est plus reliée à un Fait Vérifié. Aucun fichier n’a été téléchargé.',
  'resumePreview.validationFailure': 'Le service de validation des affirmations est indisponible. Aucun fichier n’a été téléchargé ; réessaie plus tard.',
  'resumePreview.renderFailure': 'Le moteur PDF est indisponible. Ton aperçu et tes faits vérifiés restent dans ce navigateur.',
  'operation.analyzeMatch': 'Création de ton Analyse de Correspondance…',
  'operation.extractJobRequirements': "Extraction des Exigences de l'Offre…",
  'operation.extractSourceProfile': 'Extraction des faits professionnels…',
  'operation.editResumeClaim': "Vérification de ta modification d'affirmation…",
  'operation.generateResumeClaims': 'Rédaction de ton CV Adapté…',
  'operation.importSourceDocument': 'Lecture de ton Document Source…',
  'operation.reformulateResumeClaim': "Reformulation de l'affirmation du CV…",
  'operation.retry': "Réessayer l'opération",
  'operation.retryJobPosting': "Réessayer l'Offre d'emploi",
  'operation.retryMatchAnalysis': "Réessayer l'Analyse de Correspondance",
  'operation.retrySourceProfile': 'Réessayer le Profil Source',
  'operation.retryTailoredResume': 'Réessayer le CV Adapté',
  'operation.stillWorking': 'Le traitement continue. Ton contenu reste en sécurité dans ce navigateur.',
  'privacy.retention': "Le contenu que tu ajoutes reste dans ce navigateur et expire localement après 24 heures. Les fichiers téléchargés restent sur ton appareil et ne sont pas concernés par cette expiration automatique.",
  'workflow.title': 'Ton parcours',
  'workflow.opened': 'Parcours ouvert',
  'workflow.openedDescription': 'Ton Profil Source est la prochaine étape.',
  'workflow.ready': 'Prêt à te lancer',
  'workflow.readyDescription': 'Clique sur « Commencer à adapter mon CV » pour lancer ton parcours.',
  'workflow.sourceProfile': 'Profil Source',
  'workflow.sourceProfileDescription': 'Utilise ton CV actuel ou les détails de ta carrière comme source de vérité.',
  'workflow.jobPosting': "Offre d'emploi",
  'workflow.jobPostingDescription': "Ajoute l'Offre d'emploi que tu vises pour identifier les éléments à mettre en avant.",
  'workflow.matchAnalysis': 'Analyse de Correspondance',
  'workflow.matchAnalysisDescription': 'Vérifie les preuves, la couverture et les écarts avant de générer ton CV.',
  'workflow.tailoredResume': 'CV Adapté',
  'workflow.tailoredResumeDescription': 'Relis un CV ciblé fondé uniquement sur les faits que tu as approuvés.',
  'workflow.progressLabel': "Progression de l'adaptation du CV",
  'workflow.completed': 'Terminé',
  'workflow.current': 'Étape actuelle',
  'workflow.unavailable': 'Pas encore disponible',
  'workflow.verifiedFacts': 'fait vérifié',
  'workflow.requirements': "Exigences de l'Offre",
  'workflow.matchScore': 'Score de Correspondance',
  'workflow.resumeClaims': 'affirmations du CV prêtes',
  'value.controlTitle': 'Tu gardes le contrôle',
  'value.controlText': 'Utilise uniquement les informations que tu as vérifiées et approuvées.',
  'value.focusTitle': 'Un parcours plus ciblé',
  'value.focusText': "Présente la version de ton expérience la plus pertinente.",
  'value.opportunitiesTitle': 'Conçu pour de vraies opportunités',
  'value.opportunitiesText': 'Adapte ton CV en toute confiance et postule avec intégrité.',
  'notFound.title': 'Page introuvable',
  'notFound.description': "La page demandée n'appartient pas à ce parcours d'adaptation de CV.",
  'notFound.return': 'Retourner au parcours',
} as const satisfies TranslationCatalog

export type Locale = 'en' | 'fr'

export type Localization = Readonly<{
  locale: Locale
  preferencePersistenceError: 'unavailable' | null
  readiness: 'pending' | 'ready'
  selectLocale: (locale: Locale) => void
  translate: (key: TranslationKey) => string
}>

export type LocalizationResult =
  | Readonly<{ ok: true; value: Localization }>
  | Readonly<{ ok: false; error: 'provider-missing' }>

type LocaleState = Pick<Localization, 'locale' | 'preferencePersistenceError' | 'readiness'>
type BrowserStorageResult<TValue> =
  | Readonly<{ ok: true; value: TValue }>
  | Readonly<{ ok: false; error: 'unavailable' }>

const catalogs: Readonly<Record<Locale, Partial<TranslationCatalog>>> = {
  en: englishCatalog,
  fr: frenchCatalog,
}
const defaultLocale: Locale = 'en'
const localeStorageKey = 'honest-resume-locale'
const pendingLocaleState = {
  locale: defaultLocale,
  preferencePersistenceError: null,
  readiness: 'pending',
} as const satisfies LocaleState
const LocalizationContext = createContext<Localization | null>(null)

export function LocalizationProvider({ children }: Readonly<{ children: ReactNode }>) {
  const [localeState, setLocaleState] = useState<LocaleState>(pendingLocaleState)
  useEffect(() => {
    setLocaleState(readInitialLocale())
  }, [])
  return (
    <LocalizationContext.Provider value={{
      ...localeState,
      selectLocale: (selectedLocale) => {
        selectLocale({ selectedLocale, setLocaleState })
      },
      translate: (key) => readTranslation({ locale: localeState.locale, key }),
    }}>
      {children}
    </LocalizationContext.Provider>
  )
}

export function useLocalization() {
  const localization = useContext(LocalizationContext)
  if (localization === null) return missingProviderResult
  return { ok: true, value: localization } as const
}

export const defaultDocumentTitle = englishCatalog['brand.name']
export const localizationUnavailableMessage = englishCatalog['locale.unavailable']

export function LocalizationFailure() {
  return <p role="alert">{localizationUnavailableMessage}</p>
}

function readInitialLocale(): LocaleState {
  const storedLocale = readStoredLocale()
  if (storedLocale.ok && storedLocale.value !== null) {
    return createReadyLocaleState({ locale: storedLocale.value, persistenceError: null })
  }
  return createReadyLocaleState({
    locale: readSupportedLocale({ languages: navigator.languages }),
    persistenceError: storedLocale.ok ? null : storedLocale.error,
  })
}

function readStoredLocale(): BrowserStorageResult<Locale | null> {
  try {
    const storedLocale = localStorage.getItem(localeStorageKey)
    return { ok: true, value: parseLocale({ value: storedLocale }) }
  } catch {
    return { ok: false, error: 'unavailable' }
  }
}

function readSupportedLocale({ languages }: Readonly<{ languages: readonly string[] }>): Locale {
  for (const language of languages) {
    const [languageCode] = language.toLowerCase().split('-')
    const locale = parseLocale({ value: languageCode })
    if (locale !== null) return locale
  }
  return defaultLocale
}

function parseLocale({ value }: Readonly<{ value: string | null | undefined }>): Locale | null {
  return value === 'en' || value === 'fr' ? value : null
}

function selectLocale({
  selectedLocale,
  setLocaleState,
}: Readonly<{
  selectedLocale: Locale
  setLocaleState: (state: LocaleState) => void
}>) {
  const persistenceResult = storeLocale({ selectedLocale })
  setLocaleState(createReadyLocaleState({
    locale: selectedLocale,
    persistenceError: persistenceResult.ok ? null : persistenceResult.error,
  }))
}

function storeLocale({
  selectedLocale,
}: Readonly<{ selectedLocale: Locale }>): BrowserStorageResult<undefined> {
  try {
    localStorage.setItem(localeStorageKey, selectedLocale)
    return { ok: true, value: undefined }
  } catch {
    return { ok: false, error: 'unavailable' }
  }
}

function createReadyLocaleState({
  locale,
  persistenceError,
}: Readonly<{
  locale: Locale
  persistenceError: LocaleState['preferencePersistenceError']
}>): LocaleState {
  return { locale, preferencePersistenceError: persistenceError, readiness: 'ready' }
}

function readTranslation({ locale, key }: Readonly<{ locale: Locale; key: TranslationKey }>) {
  const translation = catalogs[locale][key]
  if (translation !== undefined) return translation
  if (import.meta.env.DEV) {
    console.error(`Missing ${locale} translation: ${key}`)
    return `[Missing ${locale} translation: ${key}]`
  }
  return englishCatalog[key]
}

const missingProviderResult = {
  ok: false,
  error: 'provider-missing',
} as const satisfies LocalizationResult
