import { createContext, useContext, useEffect, useState } from 'react'
import type { ReactNode } from 'react'

const englishCatalog = {
  'candidateJourney.operation.renderingResumeDocument': 'Preparing the PDF preview',
  'combinedIntake.outdated': 'Your documents changed. Generate again to update your resume.',
  "combinedIntake.title": "Your resume and the job posting",
  "combinedIntake.description": "Drop a file or paste the text.",
  "combinedIntake.sourceTitle": "Your resume",
  "combinedIntake.sourceHint": "PDF or DOCX, up to 5 pages and 5 MB",
  "combinedIntake.sourcePlaceholder": "Paste the text of your resume or LinkedIn profile…",
  "combinedIntake.postingTitle": "The job posting",
  "combinedIntake.postingHint": "PDF or TXT",
  "combinedIntake.postingPlaceholder": "Paste the complete job posting…",
  "combinedIntake.dropFile": "Drop your file here or click to choose it",
  "combinedIntake.chooseFile": "Choose a file",
  "combinedIntake.orPaste": "or paste the text",
  "combinedIntake.removeFile": "Remove",
  "combinedIntake.rejectedFile": "This file cannot be used here. Check its format and size.",
  "combinedIntake.sourceReady": "Your resume is ready.",
  "combinedIntake.replaceSourceAction": "Replace my resume",
  "combinedIntake.keepSourceAction": "Keep my current resume",
  "combinedIntake.generate": "Generate my resume",
  "combinedIntake.regenerate": "Regenerate my resume",
  'combinedIntake.replaceSource': 'Reuse your resume, or replace it',
  "combinedIntake.replaceTitle": "Regenerate this resume?",
  'combinedIntake.replaceWarning': 'Generation replaces the current resume, including manual edits. What we took from your resume stays available.',
  "combinedIntake.confirmRegenerate": "Replace and regenerate",
  "combinedIntake.normalized": "Prepare a non-tailored resume",
  "combinedIntake.interruptedTitle": "Generation was interrupted.",
  "combinedIntake.failedTitle": "Preparation could not finish.",
  "combinedIntake.inputsKept": "Your inputs are kept.",
  "combinedIntake.inputsAndResumeKept": "Your inputs and your last resume are kept.",
  "combinedIntake.cause.source": "We could not analyze your resume.",
  "combinedIntake.cause.posting": "We could not analyze the job posting.",
  "combinedIntake.cause.evidence": "We could not link your resume to the job requirements.",
  "combinedIntake.cause.unavailable": "The service did not respond. Try again in a moment.",
  "combinedIntake.retry": "Try again",
  'failure.access-required.title': 'Your demo access has expired',
  'failure.access-required.explanation': 'The security check that protects this demo must be passed again. Your inputs are kept.',
  'failure.access-required.action': 'Pass the security check',
  'failure.rate-limited.title': 'Too many requests',
  'failure.rate-limited.explanation': 'Too many requests were sent in a short time. Wait a moment before trying again.',
  'failure.rate-limited.action': 'Try again in {seconds} s',
  'failure.rate-limited.ready': 'The wait is over. You can try again.',
  'failure.timeout.title': 'The service took too long',
  'failure.timeout.explanation': 'The operation took longer than expected. Trying again usually works.',
  'failure.timeout.action': 'Try again',
  'failure.input-too-large.title': 'Your text is too long',
  'failure.input-too-large.explanation': 'The text is longer than the service accepts. Shorten your resume or the job posting, then try again.',
  'failure.input-too-large.action': 'Shorten my text',
  'failure.service-unavailable.title': 'The service is unavailable',
  'failure.service-unavailable.explanation': 'The writing service did not answer correctly. Try again in a moment.',
  'failure.service-unavailable.action': 'Try again',
  'failure.network.title': 'Connection lost',
  'failure.network.explanation': 'Your browser could not reach the service. Check your connection, then try again.',
  'failure.network.action': 'Try again',
  'failure.unexpected.title': 'Something unexpected happened',
  'failure.unexpected.explanation': 'The service answered in an unexpected way. Reload the page; your work stays in this browser.',
  'failure.unexpected.action': 'Reload the page',
  'failure.retry': 'Try again',
  'failure.preview.layoutUnavailable': 'The PDF could not be rendered or validated. Your draft is preserved.',
  'failure.preview.pagesUnavailable': 'The PDF could not be displayed. Your draft is preserved.',
  'failure.preview.retry': 'Retry preview',
  'failure.preview.download': 'Download could not start. Your draft is preserved. Try again.',
  'failure.review.title': 'The operation could not complete. Your current content is preserved.',
  'failure.review.renew-consent': 'Renew processing consent before trying again.',
  'failure.review.correct-content': 'Correct this content or confirm it is accurate.',
  'failure.review.retry-current-draft': 'The document changed. Try again with the current version.',
  'failure.review.pageCountUnavailable': 'Page count is unavailable. Your content is preserved; try the check again.',
  'combinedIntake.omittedAmbiguities': 'Unclear details were left out. You can check and correct them below without losing the usable resume.',
  'combinedIntake.unsafe': "The generated text isn't backed by your resume. It has not replaced your resume.",
  "combinedIntake.incoherent": "Some sections repeated or contradicted one another, even after one rewrite. Try again to rewrite only those sections.",
  'combinedIntake.analysis': 'Job match and the experience behind it',
  'combinedIntake.inspection': 'See or add to what we took from your resume',
  "resultBanner.ready": "Your latest resume is ready",
  "resultBanner.preparing": "Your resume is being prepared",
  "resultBanner.view": "View",
  "resumeResult.backToDocuments": "Back to my documents",
  'combinedIntake.matching': 'Comparing your experience with the job…',
  "combinedIntake.writing": "Writing your resume section by section…",
  'resumeSections.title': 'Your resume is taking shape',
  'resumeSections.description': 'Each section appears once it is checked against your resume. Download opens when the whole resume is checked.',
  'resumeSections.keptTitle': 'Checked sections kept',
  'resumeSections.keptDescription': 'These sections are checked against your resume and kept. Trying again rewrites only the others.',
  'resumeSections.writing': 'Writing {section}…',
  'resumeSections.failed': 'Not prepared: {section}.',
  'resumeSections.failedSummary': 'Sections not prepared:',
  'resumeSections.namedSection': '{section}: {name}',
  'resumeSections.copied': 'Taken as written from your resume',
  "combinedIntake.extractingPosting": "Extracting the job requirements…",
  "combinedIntake.normalizedReady": "Non-tailored resume ready",
  "processingPolicy.consentByGeneration": "By generating, you agree that {provider} processes your professional content to write this resume.",
  "processingPolicy.grantedSummary": "Your professional content is processed by {provider}.",

  'brand.name': 'Resume Studio',
  'demoAccess.title': 'Preparing the demo',
  'demoAccess.description': 'A quick security check protects this public demo from automated abuse. No account is required.',
  'demoAccess.verifying': 'Checking access…',
  'demoAccess.retry': 'Try the security check again',
  'demoAccess.expiredTitle': 'Your demo session has expired',
  'demoAccess.expiredDescription': 'Confirm the security check to continue. Your inputs are kept and the interrupted step resumes on its own.',
  'demoAccess.abandon': 'Not now',
  'locale.unavailable': 'The interface language is unavailable.',
  'locale.switcherLabel': 'Language',
  'candidateJourney.eyebrow': 'Your resume + the job posting → a tailored resume in 1 minute',
  'candidateJourney.title': 'Your resume, tailored to the job.',
  'candidateJourney.description': 'Drop your resume and the job posting. We highlight your most relevant experience without inventing anything.',
  'candidateJourney.privacyStatement': 'Nothing is stored on our servers: your documents stay in this browser for 24 hours.',
  'candidateJourney.privacyLearnMore': 'Learn more',
  'candidateJourney.skipToContent': 'Skip to content',
  'candidateJourney.phasesLabel': 'Steps',
  'candidateJourney.sourceIntake': 'Your resume',
  'candidateJourney.sourceIntakeDescription': 'Add the professional experience that can support your application.',
  'candidateJourney.jobMatch': 'The job',
  'candidateJourney.jobMatchDescription': 'Compare your experience with one job posting.',
  'candidateJourney.tailoredResumePreparation': 'Your tailored resume',
  'candidateJourney.tailoredResumePreparationDescription': 'Prepare and export a resume backed by your experience.',
  'tailoredResume.valueProposition': 'Summary',
  'tailoredResume.experiences': 'Experience',
  'tailoredResume.language': 'Resume language',
  'tailoredResume.languageAutomatic': 'Job posting language',
  'tailoredResume.contactDetails': 'Local contact details',
  'tailoredResume.name': 'Name',
  'tailoredResume.email': 'Email',
  'tailoredResume.phone': 'Phone',
  'tailoredResume.fieldLabel': 'Resume field',
  'tailoredResume.saveField': 'Save',
  'tailoredResume.attestField': 'Confirm this is accurate',
  'tailoredResume.unsupportedField': "This edit adds something your resume doesn't mention.",
  'tailoredResume.hideField': 'Hide field',
  'tailoredResume.restoreField': 'Restore field',
  'tailoredResume.moveUp': 'Move {name} up',
  'tailoredResume.moveDown': 'Move {name} down',
  'tailoredResume.entryName': '{section}: {entry}',
  'candidateJourney.startSession': 'Get started',
  'candidateJourney.deleteSession': 'Delete my data',
  'candidateJourney.deleteDialogTitle': 'Delete your data?',
  'candidateJourney.deleteDialogDescription': 'This immediately removes your documents and resume from this browser.',
  'candidateJourney.deleteCancel': 'Cancel',
  'candidateJourney.deleteConfirm': 'Delete my data now',
  'candidateJourney.sessionDeleted': 'Your data was deleted from this browser.',
  'candidateJourney.expiredSessionDiscarded': 'Your data was deleted from this browser after 24 hours.',
  'candidateJourney.incompatibleSessionDiscarded': 'Data saved by an older version was deleted from this browser.',
  'candidateJourney.storageUnavailable': "This browser can't save your data. Check that site storage is allowed.",
  'candidateJourney.phaseAnnouncement': 'Current step: {phase}.',
  'candidateJourney.operationAnnouncement': '{operation} Your last stable result remains visible while this finishes.',
  'candidateJourney.firstOperationAnnouncement': '{operation}',
  'candidateJourney.validatedResultAnnouncement': 'Ready: {result}.',
  'candidateJourney.progressLabel': 'Progress',
  'candidateJourney.progressDescription': 'This can take up to a minute.',
  'candidateJourney.progressStep': 'Step {step} of 3 · about a minute in total.',
  'candidateJourney.operation.extractSourceProfile': 'Reading your resume…',
  'candidateJourney.operation.processingJobPosting': 'Reading the job posting and comparing it with your resume…',
  'candidateJourney.operation.processingProfileEnrichment': 'Adding your experience and updating the match…',
  'candidateJourney.operation.resolvingCriticalAmbiguity': 'Saving your answer…',
  'candidateJourney.operation.preparingTailoredResume': 'Preparing your tailored resume…',
  'candidateJourney.result.sourceProfile': 'what we took from your resume',
  'candidateJourney.result.matchAnalysis': 'your job match',
  'candidateJourney.result.tailoredResume': 'your tailored resume',
  'processingPolicy.provider': 'Provider',
  'processingPolicy.purposes': 'Purposes',
  'processingPolicy.transmittedDataCategories': 'Data sent',
  'processingPolicy.retentionPolicy': 'Retention',
  'processingPolicy.storageBehavior': 'Storage',
  'processingPolicy.version': 'Policy version',
  'processingPolicy.purpose.extractEvidence': 'Read and organize the experience in your resume',
  'processingPolicy.purpose.compareEvidence': 'Compare your experience with the job requirements',
  'processingPolicy.purpose.writeResume': 'Write and check the content of your tailored resume',
  'processingPolicy.data.minimizedProfessionalContent': 'Minimized professional content',
  'processingPolicy.data.jobPostingContent': 'Job posting content',
  'processingPolicy.data.candidateFacts': 'The information from your resume needed to compare, write and check',
  'processingPolicy.retentionValue': 'API inputs and outputs may be retained for abuse monitoring for up to 30 days, or longer when legally required.',
  'processingPolicy.storageValue': "Your content stays in this browser; model requests are stateless and the provider's application storage is disabled.",
  'sourceIntake.title': 'Add your resume',
  'sourceIntake.description': 'Upload a text-based PDF or DOCX, or paste professional text. Contact details stay in this browser.',
  'sourceIntake.pasteMethod': 'Paste text',
  'sourceIntake.uploadMethod': 'Upload PDF or DOCX',
  'sourceIntake.professionalText': 'Professional text',
  'sourceIntake.professionalTextPlaceholder': 'Paste your experience, projects, skills, education, languages, and certifications',
  'sourceIntake.sourceFile': 'Your resume file',
  'sourceIntake.sourceFileHint': 'Choose a PDF or DOCX (maximum five pages)',
  'sourceIntake.submit': 'Read my resume',
  'sourceIntake.ready': 'Your resume has been read.',
  'sourceIntake.inspectProfile': 'See what we took from your resume',
  'sourceIntake.hideProfile': 'Hide what we took from your resume',
  'sourceIntake.detailedProfile': 'What we took from your resume',
  'sourceIntake.ambiguities': 'A few things to clarify',
  'sourceIntake.answerAmbiguity': 'Save this answer',
  'sourceIntake.experiences': 'Experiences',
  'sourceIntake.projects': 'Projects',
  'sourceIntake.skills': 'Skills',
  'sourceIntake.education': 'Education',
  'sourceIntake.languages': 'Languages',
  'sourceIntake.certifications': 'Certifications',
  'sourceIntake.failure.ambiguity': 'This question is no longer available.',
  'sourceIntake.failure.storage': "Your resume couldn't be saved in this browser.",
  'sourceIntake.failure.encrypted': 'This document is encrypted. Upload an unlocked copy or paste its text.',
  'sourceIntake.failure.empty': 'Add your resume as a file or pasted text before continuing.',
  'sourceIntake.failure.invalid': 'This document is invalid. Export a new PDF or DOCX and try again.',
  'sourceIntake.failure.oversized': 'Use a document of at most five pages and 5 MB, or paste up to 50,000 characters.',
  'sourceIntake.failure.consent': 'Accept how your data is processed before we read your resume.',
  'sourceIntake.failure.scanned': 'This PDF appears to be a scan. Use a PDF with selectable text or paste the text.',
  'sourceIntake.failure.extraction': "Your resume couldn't be read. Nothing was lost; try again.",
  'sourceIntake.failure.unreadable': 'This document could not be read. Upload another copy or paste the text.',
  'sourceIntake.failure.unsupported': 'Only text-based PDF, DOCX, and pasted text are supported.',
  'jobMatch.title': 'Analyze a job posting',
  'jobMatch.textLabel': 'Job posting text',
  'jobMatch.fileLabel': 'Job posting file',
  'jobMatch.targetRole': 'Target role',
  'jobMatch.measurement': "This score shows how well your experience covers the job's stated requirements. It is not a hiring probability.",
  'jobMatch.strengths': 'Three strongest matches',
  'jobMatch.gaps': 'Three priority gaps',
  'jobMatch.criticalReserve': 'Reservation on an essential requirement',
  'jobMatch.criticalReserve.clear': 'Every critical requirement is backed by your resume.',
  'jobMatch.criticalReserve.present': 'One or more critical requirements are partial or unsupported. Read these gaps before deciding to apply.',
  'jobMatch.constraints': 'Important practical constraints',
  'jobMatch.constraints.none': 'No explicit practical constraint was found.',
  'jobMatch.details': 'All requirements and the experience that meets them',
  'jobMatch.importance.critical': 'Critical',
  'jobMatch.importance.central': 'Central',
  'jobMatch.importance.complementary': 'Complementary',
  'jobMatch.coverage.covered': 'Covered',
  'jobMatch.coverage.partially-covered': 'Partially covered',
  'jobMatch.coverage.uncovered': 'Uncovered',
  'jobMatch.sourceExcerpt': 'Exact source excerpt',
  'jobMatch.evidence': 'Your experience',
  'jobMatch.evidence.none': 'Nothing in your resume supports it.',
  'jobMatch.adjacentEvidence': 'Related experience you can highlight instead (it does not meet this requirement)',
  'jobMatch.failure.empty': 'Add the job posting text before continuing.',
  'jobMatch.failure.invalid': 'This job posting file is invalid.',
  'jobMatch.failure.oversized': 'Use a job posting smaller than 5 MB and 100,000 characters.',
  'jobMatch.failure.scanned': 'This PDF appears to be a scan. Use a PDF with selectable text or paste the text.',
  'jobMatch.failure.unsupported': "Only pasted text, text-based PDF and TXT job postings are supported. Links can't be read.",
  'jobMatch.failure.unreadable': "This job posting couldn't be read. Upload another copy or paste the text.",
  'jobMatch.failure.extraction': "The job posting couldn't be analyzed. Your previous result is kept; try again.",
  'jobMatch.failure.evidence': "Your experience couldn't be compared with the job. Your previous result is kept; try again.",
  'jobMatch.failure.consent': 'Accept how your data is processed before we analyze a job posting.',
  'jobMatch.failure.storage': "The job match couldn't be saved in this browser.",
  'jobMatch.enrichmentUnavailable': "You can't add experience for this requirement.",
  'jobMatch.generation.denied': 'Nothing in your resume matches this job closely enough to tailor it.',
  'jobMatch.generation.lowScoreWarning': 'A low match score is a warning, not a reason to stop.',
  'jobMatch.generation.normalizedNotice': 'Only a general version of your resume, not tailored to the job, is available.',
  'sourceProfile.kind.experience': 'Experience',
  'sourceProfile.kind.skill': 'Skill',
  'sourceProfile.kind.education': 'Education',
  'sourceProfile.kind.certification': 'Certification',
  'sourceProfile.kind.language': 'Language',
  'sourceProfile.kind.project': 'Project',
  'matchAnalysis.score': 'Match score',
  'matchAnalysis.band.strong': 'Strong match',
  'matchAnalysis.band.credible': 'Credible match',
  'matchAnalysis.band.ambitious': 'Ambitious match',
  'matchAnalysis.enrichmentTitle': 'Add missing experience (optional)',
  'matchAnalysis.enrichmentDescription': 'Add only real professional experience your resume leaves out. The three most important gaps come first.',
  'matchAnalysis.enrichmentQuestion': 'Do you have real professional experience that meets this requirement?',
  'matchAnalysis.enrichmentAnswer': 'Describe only what you actually did',
  'matchAnalysis.enrichmentKind': 'Type of experience',
  'matchAnalysis.enrichmentAdd': 'Add this experience and update',
  'matchAnalysis.enrichmentDuplicateFailure': 'This is already in your resume. Your previous match is kept.',
  'matchAnalysis.enrichmentInvalidFailure': 'Describe your experience or skip this question. Your previous match is kept.',
  'notFound.title': 'Page not found',
  'notFound.description': "The page you requested doesn't exist.",
  'notFound.return': 'Back to home',
  'safetyNet.title': 'Something went wrong',
  'safetyNet.explanation': 'This page stopped working. Your documents stay in this browser: reload the page to continue where you left off.',
  'safetyNet.reload': 'Reload',
  'safetyNet.returnToDocuments': 'Back to my documents',
  'resumeReview.preview': 'Preview your resume',
  'resumeReview.description': 'Review the document first. Open the editor only when you want to change something.',
  'resumeReview.hideEntry': 'Hide experience',
  'resumeReview.restoreEntry': 'Restore experience',
  'resumeReview.edit': 'Edit resume',
  'resumeReview.close': 'Close editor',
  'resumeReview.contacts': 'Identity and contact details',
  'resumeReview.recovery': 'Hidden items',
  'resumeReview.order': 'Section order',
  'resumeReview.hidden': 'Hidden content',
  'resumeReview.omitted': 'Not used in this resume',
  'resumeReview.restore': 'Add to the resume',
  'resumeReview.emptyRecovery': 'Everything from your resume is already included.',
  'resumeReview.localContacts': 'Identity and contact details stay in your browser and are never sent to the writing service.',
  'resumeReview.condense': 'Propose a shorter version',
  'resumeReview.changeJobPosting': 'Change job posting',
  'resumeReview.proposal': 'Shorter version proposal',
  'resumeReview.proposalDescription': 'Your current resume stays unchanged until you accept this proposal.',
  'resumeReview.accept': 'Accept shorter version',
  'resumeReview.reject': 'Keep current version',
  'resumeReview.checking': 'Checking the current document…',
  'resumeReview.validating': 'Checking the edited section…',
  'resumeReview.condensing': 'Preparing a shorter proposal…',
  'resumeReview.unchecked': 'Page count has not been checked for this version.',
  'resumeReview.shortening': 'Shortening the resume…',
  'resumeReview.reviewHidden': 'Review hidden content',
  'resumeReview.hiddenByReduction': 'Hidden to fit the page',
  'resumeReview.section.value-proposition': 'Summary',
  'resumeReview.section.experiences': 'Experience',
  'resumeReview.section.skills': 'Skills',
  'resumeReview.section.education': 'Education',
  'resumeReview.section.certifications': 'Certifications',
  'resumeReview.section.languages': 'Languages',
  'resumeReview.section.projects': 'Projects',
  'resumeReview.saved': 'Resume updated.',
  'resumeReview.hiddenNotice': 'Content hidden from the resume.',
  'resumeReview.restored': 'Content restored.',
  'resumeReview.ordered': 'Order updated.',
  'resumeReview.usability': 'Can you apply with this PDF without restructuring it?',
  'resumeReview.usable': 'Yes, usable as is',
  'resumeReview.needsRewriting': 'No, it needs structural rewriting',
  'resumeReview.usabilityRecorded': 'Thank you. Only your answer was recorded, never your resume content.',
  'resumePreview.photo': 'Optional photo',
  'resumePreview.photoInvalid': 'Choose a PNG, JPEG or WebP image smaller than 1 MB.',
  'resumePreview.photoAdd': 'Add a photo',
  'resumePreview.photoChange': 'Change photo',
  'resumePreview.photoRemove': 'Remove',
  'resumePreview.photoHint': 'PNG, JPEG or WebP, under 1 MB.',
  'resumePreview.title': 'Preview and export',
  'resumePreview.pending': 'Preparing and checking the current PDF…',
  'resumePreview.download': 'Download PDF',
  'resumePreview.page': 'Page',
  'resumePreview.textVersion': 'Read the document text',
  'resumePreview.previewTitle': 'Tailored resume preview',
  'resumePreview.downloaded': 'PDF handed to your browser for download.',
  'resumePreview.unsupported-content': 'Resolve or confirm the unsupported professional changes before downloading.',
  'resumePreview.fullName': 'Full name',
  'resumePreview.detectedName': 'Taken from your resume, check the spelling.',
  'resumePreview.missing-identity': 'Add your full name to download the PDF.',
  'resumePreview.missing-contact': 'Add an email address or phone number in contact details.',
  'resumePreview.stale-layout': 'The document changed. Wait for the current preview before downloading.',
  'resumePreview.paused': 'Close the editor to download the current PDF.',
  'resumePreview.copiedExperiences': 'Experiences taken as written',
  'pageBudget.fitsOne': 'Fits on one page.',
  'pageBudget.fitsTwo': 'Fits on two pages.',
  'pageBudget.overflow': 'Your resume runs to {pageCount} pages, two at most.',
  'pageBudget.proposalOverflow': 'This proposal still runs over two pages.',
  'pageBudget.shorten': 'Shorten the resume',
} as const

type TranslationKey = keyof typeof englishCatalog
type TranslationCatalog = Readonly<Record<TranslationKey, string>>

const frenchCatalog = {
  'combinedIntake.outdated': 'Tes documents ont changé. Régénère pour mettre ton CV à jour.',
  "combinedIntake.title": "Ton CV et l’offre d’emploi",
  "combinedIntake.description": "Dépose un fichier ou colle le texte.",
  "combinedIntake.sourceTitle": "Ton CV",
  "combinedIntake.sourceHint": "PDF ou DOCX, 5 pages et 5 Mo maximum",
  "combinedIntake.sourcePlaceholder": "Colle ici le texte de ton CV ou de ton profil LinkedIn…",
  "combinedIntake.postingTitle": "L’offre d’emploi",
  "combinedIntake.postingHint": "PDF ou TXT",
  "combinedIntake.postingPlaceholder": "Colle ici l’offre complète…",
  "combinedIntake.dropFile": "Glisse ton fichier ici ou clique pour le choisir",
  "combinedIntake.chooseFile": "Choisis un fichier",
  "combinedIntake.orPaste": "ou colle le texte",
  "combinedIntake.removeFile": "Retirer",
  "combinedIntake.rejectedFile": "Ce fichier ne peut pas être utilisé ici. Vérifie son format et sa taille.",
  "combinedIntake.sourceReady": "Ton CV est prêt.",
  "combinedIntake.replaceSourceAction": "Remplacer mon CV",
  "combinedIntake.keepSourceAction": "Garder mon CV actuel",
  "combinedIntake.generate": "Générer mon CV",
  "combinedIntake.regenerate": "Générer à nouveau mon CV",
  'combinedIntake.replaceSource': 'Réutiliser ton CV ou le remplacer',
  "combinedIntake.replaceTitle": "Régénérer ce CV ?",
  'combinedIntake.replaceWarning': 'La génération remplace le CV actuel, y compris les modifications manuelles. Ce qu’on a retenu de ton CV reste disponible.',
  "combinedIntake.confirmRegenerate": "Remplacer et régénérer",
  "combinedIntake.normalized": "Préparer un CV non adapté",
  "combinedIntake.interruptedTitle": "La génération a été interrompue.",
  "combinedIntake.failedTitle": "La préparation n’a pas abouti.",
  "combinedIntake.inputsKept": "Tes entrées sont conservées.",
  "combinedIntake.inputsAndResumeKept": "Tes entrées et ton dernier CV sont conservés.",
  "combinedIntake.cause.source": "On n’a pas réussi à analyser ton CV.",
  "combinedIntake.cause.posting": "On n’a pas réussi à analyser l’offre d’emploi.",
  "combinedIntake.cause.evidence": "On n’a pas réussi à relier ton CV aux exigences de l’offre.",
  "combinedIntake.cause.unavailable": "Le service n’a pas répondu. Réessaie dans un instant.",
  "combinedIntake.retry": "Réessayer",
  'failure.access-required.title': 'Ton accès à la démo a expiré',
  'failure.access-required.explanation': 'La vérification de sécurité qui protège cette démo doit être repassée. Tes données sont conservées.',
  'failure.access-required.action': 'Repasser la vérification',
  'failure.rate-limited.title': 'Trop de demandes',
  'failure.rate-limited.explanation': 'Trop de demandes ont été envoyées en peu de temps. Patiente un instant avant de réessayer.',
  'failure.rate-limited.action': 'Réessayer dans {seconds} s',
  'failure.rate-limited.ready': 'L’attente est terminée. Tu peux réessayer.',
  'failure.timeout.title': 'Le service a mis trop de temps',
  'failure.timeout.explanation': 'L’opération a pris plus de temps que prévu. Réessayer suffit généralement.',
  'failure.timeout.action': 'Réessayer',
  'failure.input-too-large.title': 'Ton texte est trop long',
  'failure.input-too-large.explanation': 'Le texte dépasse ce que le service accepte. Raccourcis ton CV ou l’offre d’emploi, puis réessaie.',
  'failure.input-too-large.action': 'Raccourcir mon texte',
  'failure.service-unavailable.title': 'Le service est indisponible',
  'failure.service-unavailable.explanation': 'Le service de rédaction n’a pas répondu correctement. Réessaie dans un instant.',
  'failure.service-unavailable.action': 'Réessayer',
  'failure.network.title': 'Connexion perdue',
  'failure.network.explanation': 'Ton navigateur n’a pas pu joindre le service. Vérifie ta connexion, puis réessaie.',
  'failure.network.action': 'Réessayer',
  'failure.unexpected.title': 'Un problème inattendu est survenu',
  'failure.unexpected.explanation': 'Le service a répondu de façon inattendue. Recharge la page ; ton travail reste dans ce navigateur.',
  'failure.unexpected.action': 'Recharger la page',
  'failure.retry': 'Réessayer',
  'failure.preview.layoutUnavailable': 'Le PDF n’a pas pu être produit ou validé. Ton brouillon est conservé.',
  'failure.preview.pagesUnavailable': 'Le PDF n’a pas pu être affiché. Ton brouillon est conservé.',
  'failure.preview.retry': 'Réessayer l’aperçu',
  'failure.preview.download': 'Le téléchargement n’a pas pu démarrer. Ton brouillon est conservé. Réessaie.',
  'failure.review.title': 'L’opération n’a pas abouti. Ton contenu actuel est conservé.',
  'failure.review.renew-consent': 'Renouvelle ton consentement au traitement avant de réessayer.',
  'failure.review.correct-content': 'Corrige ce contenu ou confirme qu’il est exact.',
  'failure.review.retry-current-draft': 'Le document a changé. Réessaie avec la version actuelle.',
  'failure.review.pageCountUnavailable': 'Le nombre de pages est indisponible. Ton contenu est conservé ; relance la vérification.',
  'combinedIntake.omittedAmbiguities': 'Des éléments ambigus ont été laissés de côté. Tu peux les vérifier et les corriger ci-dessous sans perdre le CV utilisable.',
  'combinedIntake.unsafe': 'Le contenu généré n’est pas appuyé par ton CV. Il n’a pas remplacé ton CV.',
  "combinedIntake.incoherent": "Certaines rubriques se répétaient ou se contredisaient, même après une réécriture. Réessaie pour réécrire seulement ces rubriques.",
  'combinedIntake.analysis': 'Correspondance avec l’offre et expériences qui y répondent',
  'combinedIntake.inspection': 'Voir ou compléter ce qu’on a retenu de ton CV',
  "resultBanner.ready": "Ton dernier CV est prêt",
  "resultBanner.preparing": "Ton CV est en cours de préparation",
  "resultBanner.view": "Voir",
  "resumeResult.backToDocuments": "Revenir à mes documents",
  'combinedIntake.matching': 'Comparaison de ton expérience avec l’offre…',
  "combinedIntake.writing": "Rédaction de ton CV section par section…",
  'resumeSections.title': 'Ton CV prend forme',
  'resumeSections.description': 'Chaque rubrique apparaît dès qu’elle est vérifiée par rapport à ton CV. Le téléchargement s’ouvre quand tout le CV est vérifié.',
  'resumeSections.keptTitle': 'Rubriques vérifiées conservées',
  'resumeSections.keptDescription': 'Ces rubriques sont vérifiées par rapport à ton CV et conservées. Une nouvelle tentative ne réécrit que les autres.',
  'resumeSections.writing': 'Rédaction : {section}…',
  'resumeSections.failed': 'Rubrique non préparée : {section}.',
  'resumeSections.failedSummary': 'Rubriques non préparées :',
  'resumeSections.namedSection': '{section} : {name}',
  'resumeSections.copied': 'Repris tel quel de ton CV',
  "combinedIntake.extractingPosting": "Extraction des exigences de l’offre…",
  "combinedIntake.normalizedReady": "CV non adapté prêt",
  "processingPolicy.consentByGeneration": "En générant, tu acceptes qu’{provider} traite ton contenu professionnel pour rédiger ce CV.",
  "processingPolicy.grantedSummary": "Ton contenu professionnel est traité par {provider}.",

  'brand.name': 'Resume Studio',
  'demoAccess.title': 'Préparation de la démo',
  'demoAccess.description': 'Une vérification rapide protège cette démo publique contre les abus automatisés. Aucun compte n’est nécessaire.',
  'demoAccess.verifying': 'Vérification de l’accès…',
  'demoAccess.retry': 'Relancer la vérification de sécurité',
  'demoAccess.expiredTitle': 'Ta session de démo a expiré',
  'demoAccess.expiredDescription': 'Valide la vérification de sécurité pour continuer. Tes entrées sont conservées et l’étape interrompue reprend d’elle-même.',
  'demoAccess.abandon': 'Plus tard',
  'locale.unavailable': 'La langue de l’interface n’est pas disponible.',
  'locale.switcherLabel': 'Langue',
  'candidateJourney.eyebrow': 'Ton CV + l’offre → un CV ciblé en 1 minute',
  'candidateJourney.title': 'Ton CV, taillé pour l’offre.',
  'candidateJourney.description': "Dépose ton CV et l’offre d’emploi. On met en avant tes expériences les plus pertinentes, sans rien inventer.",
  'candidateJourney.privacyStatement': 'Rien n’est stocké sur nos serveurs : tes documents restent 24 heures dans ce navigateur.',
  'candidateJourney.privacyLearnMore': 'En savoir plus',
  'candidateJourney.skipToContent': 'Aller au contenu',
  'candidateJourney.phasesLabel': 'Étapes',
  'candidateJourney.sourceIntake': 'Ton CV',
  'candidateJourney.sourceIntakeDescription': 'Ajoute l’expérience professionnelle qui peut appuyer ta candidature.',
  'candidateJourney.jobMatch': 'L’offre',
  'candidateJourney.jobMatchDescription': 'Compare ton expérience à une offre d’emploi.',
  'candidateJourney.tailoredResumePreparation': 'Ton CV adapté',
  'candidateJourney.tailoredResumePreparationDescription': 'Prépare et exporte un CV fondé sur ton expérience.',
  'tailoredResume.valueProposition': 'Profil',
  'tailoredResume.experiences': 'Expérience',
  'tailoredResume.language': 'Langue du CV',
  'tailoredResume.languageAutomatic': 'Langue de l’offre',
  'tailoredResume.contactDetails': 'Coordonnées locales',
  'tailoredResume.name': 'Nom',
  'tailoredResume.email': 'E-mail',
  'tailoredResume.phone': 'Téléphone',
  'tailoredResume.fieldLabel': 'Champ du CV',
  'tailoredResume.saveField': 'Enregistrer',
  'tailoredResume.attestField': 'Confirmer que c’est exact',
  'tailoredResume.unsupportedField': 'Cette modification ajoute une information absente de ton CV.',
  'tailoredResume.hideField': 'Masquer le champ',
  'tailoredResume.restoreField': 'Restaurer le champ',
  'tailoredResume.moveUp': 'Monter {name}',
  'tailoredResume.moveDown': 'Descendre {name}',
  'tailoredResume.entryName': '{section} : {entry}',
  'candidateJourney.startSession': 'Commencer',
  'candidateJourney.deleteSession': 'Effacer mes données',
  'candidateJourney.deleteDialogTitle': 'Effacer tes données ?',
  'candidateJourney.deleteDialogDescription': 'Tes documents et ton CV seront immédiatement supprimés de ce navigateur.',
  'candidateJourney.deleteCancel': 'Annuler',
  'candidateJourney.deleteConfirm': 'Effacer mes données maintenant',
  'candidateJourney.sessionDeleted': 'Tes données ont été supprimées de ce navigateur.',
  'candidateJourney.expiredSessionDiscarded': 'Tes données ont été supprimées de ce navigateur après 24 heures.',
  'candidateJourney.incompatibleSessionDiscarded': 'Des données enregistrées par une ancienne version ont été supprimées de ce navigateur.',
  'candidateJourney.storageUnavailable': 'Ce navigateur ne peut pas enregistrer tes données. Vérifie que le stockage du site est autorisé.',
  'candidateJourney.phaseAnnouncement': 'Étape en cours : {phase}.',
  'candidateJourney.operationAnnouncement': '{operation} Ton dernier résultat stable reste visible pendant le traitement.',
  'candidateJourney.firstOperationAnnouncement': '{operation}',
  'candidateJourney.validatedResultAnnouncement': 'Prêt : {result}.',
  'candidateJourney.progressLabel': 'Progression',
  'candidateJourney.progressDescription': 'Ça peut prendre jusqu’à une minute.',
  'candidateJourney.progressStep': 'Étape {step} sur 3 · environ une minute au total.',
  'candidateJourney.operation.extractSourceProfile': 'Lecture de ton CV…',
  'candidateJourney.operation.processingJobPosting': 'Lecture de l’offre et comparaison avec ton CV…',
  'candidateJourney.operation.processingProfileEnrichment': 'Ajout de ton expérience et mise à jour de la correspondance…',
  'candidateJourney.operation.resolvingCriticalAmbiguity': 'Enregistrement de ta réponse…',
  'candidateJourney.operation.renderingResumeDocument': 'Préparation de l’aperçu PDF',
  'candidateJourney.operation.preparingTailoredResume': 'Préparation de ton CV adapté…',
  'candidateJourney.result.sourceProfile': 'ce qu’on a retenu de ton CV',
  'candidateJourney.result.matchAnalysis': 'ta correspondance avec l’offre',
  'candidateJourney.result.tailoredResume': 'ton CV adapté',
  'processingPolicy.provider': 'Fournisseur',
  'processingPolicy.purposes': 'Finalités',
  'processingPolicy.transmittedDataCategories': 'Données envoyées',
  'processingPolicy.retentionPolicy': 'Conservation',
  'processingPolicy.storageBehavior': 'Stockage',
  'processingPolicy.version': 'Version de la politique',
  'processingPolicy.purpose.extractEvidence': 'Lire et organiser l’expérience présente dans ton CV',
  'processingPolicy.purpose.compareEvidence': 'Comparer ton expérience aux exigences de l’offre',
  'processingPolicy.purpose.writeResume': 'Rédiger et vérifier le contenu de ton CV adapté',
  'processingPolicy.data.minimizedProfessionalContent': 'Contenu professionnel minimisé',
  'processingPolicy.data.jobPostingContent': 'Contenu de l’offre d’emploi',
  'processingPolicy.data.candidateFacts': 'Les informations de ton CV nécessaires pour comparer, rédiger et vérifier',
  'processingPolicy.retentionValue': "Les entrées et sorties de l’API peuvent être conservées jusqu’à 30 jours pour surveiller les abus, ou plus longtemps si la loi l’exige.",
  'processingPolicy.storageValue': 'Ton contenu reste dans ce navigateur ; les requêtes au modèle sont sans état et le stockage côté fournisseur est désactivé.',
  'sourceIntake.title': 'Ajoute ton CV',
  'sourceIntake.description': 'Importe un PDF texte ou un DOCX, ou colle du texte professionnel. Tes coordonnées restent dans ce navigateur.',
  'sourceIntake.pasteMethod': 'Coller du texte',
  'sourceIntake.uploadMethod': 'Importer un PDF ou DOCX',
  'sourceIntake.professionalText': 'Texte professionnel',
  'sourceIntake.professionalTextPlaceholder': 'Colle tes expériences, projets, compétences, formations, langues et certifications',
  'sourceIntake.sourceFile': 'Fichier de ton CV',
  'sourceIntake.sourceFileHint': 'Choisis un PDF ou DOCX (cinq pages maximum)',
  'sourceIntake.submit': 'Lire mon CV',
  'sourceIntake.ready': 'Ton CV a été lu.',
  'sourceIntake.inspectProfile': 'Voir ce qu’on a retenu de ton CV',
  'sourceIntake.hideProfile': 'Masquer ce qu’on a retenu de ton CV',
  'sourceIntake.detailedProfile': 'Ce qu’on a retenu de ton CV',
  'sourceIntake.ambiguities': 'Quelques points à préciser',
  'sourceIntake.answerAmbiguity': 'Enregistrer cette réponse',
  'sourceIntake.experiences': 'Expériences',
  'sourceIntake.projects': 'Projets',
  'sourceIntake.skills': 'Compétences',
  'sourceIntake.education': 'Formation',
  'sourceIntake.languages': 'Langues',
  'sourceIntake.certifications': 'Certifications',
  'sourceIntake.failure.ambiguity': 'Cette question n’est plus disponible.',
  'sourceIntake.failure.storage': 'Ton CV n’a pas pu être enregistré dans ce navigateur.',
  'sourceIntake.failure.encrypted': 'Ce document est chiffré. Importe une copie déverrouillée ou colle son texte.',
  'sourceIntake.failure.empty': 'Ajoute ton CV, en fichier ou en texte collé, avant de continuer.',
  'sourceIntake.failure.invalid': 'Ce document est invalide. Exporte un nouveau PDF ou DOCX puis réessaie.',
  'sourceIntake.failure.oversized': 'Utilise un document de cinq pages et 5 Mo maximum, ou colle jusqu’à 50 000 caractères.',
  'sourceIntake.failure.consent': 'Accepte le traitement de tes données avant qu’on lise ton CV.',
  'sourceIntake.failure.scanned': 'Ce PDF semble être un scan. Utilise un PDF avec du texte sélectionnable ou colle le texte.',
  'sourceIntake.failure.extraction': 'Ton CV n’a pas pu être lu. Rien n’est perdu ; réessaie.',
  'sourceIntake.failure.unreadable': 'Ce document n’a pas pu être lu. Importe une autre copie ou colle le texte.',
  'sourceIntake.failure.unsupported': 'Seuls les PDF texte, DOCX et textes collés sont pris en charge.',
  'jobMatch.title': 'Analyse une offre d’emploi',
  'jobMatch.textLabel': 'Texte de l’offre d’emploi',
  'jobMatch.fileLabel': 'Fichier de l’offre d’emploi',
  'jobMatch.targetRole': 'Poste ciblé',
  'jobMatch.measurement': 'Ce score indique dans quelle mesure ton expérience couvre les exigences de l’offre. Ce n’est pas une probabilité d’embauche.',
  'jobMatch.strengths': 'Trois correspondances les plus fortes',
  'jobMatch.gaps': 'Trois écarts prioritaires',
  'jobMatch.criticalReserve': 'Réserve sur une exigence essentielle',
  'jobMatch.criticalReserve.clear': 'Chaque exigence critique est appuyée par ton CV.',
  'jobMatch.criticalReserve.present': 'Une ou plusieurs exigences critiques sont partielles ou non étayées. Lis ces écarts avant de décider de postuler.',
  'jobMatch.constraints': 'Contraintes pratiques importantes',
  'jobMatch.constraints.none': 'Aucune contrainte pratique explicite n’a été trouvée.',
  'jobMatch.details': 'Toutes les exigences et les expériences qui y répondent',
  'jobMatch.importance.critical': 'Critique',
  'jobMatch.importance.central': 'Centrale',
  'jobMatch.importance.complementary': 'Complémentaire',
  'jobMatch.coverage.covered': 'Couverte',
  'jobMatch.coverage.partially-covered': 'Partiellement couverte',
  'jobMatch.coverage.uncovered': 'Non couverte',
  'jobMatch.sourceExcerpt': 'Extrait source exact',
  'jobMatch.evidence': 'Ton expérience',
  'jobMatch.evidence.none': 'Rien dans ton CV ne l’appuie.',
  'jobMatch.adjacentEvidence': 'Expérience proche à mettre en avant à la place (elle ne remplit pas cette exigence)',
  'jobMatch.failure.empty': 'Ajoute le texte de l’offre d’emploi avant de continuer.',
  'jobMatch.failure.invalid': 'Ce fichier d’offre d’emploi est invalide.',
  'jobMatch.failure.oversized': 'Utilise une offre d’emploi de moins de 5 Mo et 100 000 caractères.',
  'jobMatch.failure.scanned': 'Ce PDF semble scanné. Utilise un PDF avec du texte sélectionnable ou colle le texte.',
  'jobMatch.failure.unsupported': 'Seuls le texte collé, les PDF texte et les fichiers TXT sont pris en charge. Les liens ne peuvent pas être lus.',
  'jobMatch.failure.unreadable': 'Cette offre d’emploi est illisible. Importe une autre copie ou colle le texte.',
  'jobMatch.failure.extraction': 'L’offre d’emploi n’a pas pu être analysée. Ton résultat précédent est conservé ; réessaie.',
  'jobMatch.failure.evidence': 'Ton expérience n’a pas pu être comparée à l’offre. Ton résultat précédent est conservé ; réessaie.',
  'jobMatch.failure.consent': 'Accepte le traitement de tes données avant qu’on analyse une offre d’emploi.',
  'jobMatch.failure.storage': 'La correspondance avec l’offre n’a pas pu être enregistrée dans ce navigateur.',
  'jobMatch.enrichmentUnavailable': 'Tu ne peux pas ajouter d’expérience pour cette exigence.',
  'jobMatch.generation.denied': 'Rien dans ton CV ne correspond assez à cette offre pour l’adapter.',
  'jobMatch.generation.lowScoreWarning': 'Un score de correspondance faible est un avertissement, pas un blocage.',
  'jobMatch.generation.normalizedNotice': 'Seule une version générale de ton CV, non adaptée à l’offre, est disponible.',
  'sourceProfile.kind.experience': 'Expérience',
  'sourceProfile.kind.skill': 'Compétence',
  'sourceProfile.kind.education': 'Formation',
  'sourceProfile.kind.certification': 'Certification',
  'sourceProfile.kind.language': 'Langue',
  'sourceProfile.kind.project': 'Projet',
  'matchAnalysis.score': 'Score de correspondance',
  'matchAnalysis.band.strong': 'Correspondance forte',
  'matchAnalysis.band.credible': 'Correspondance crédible',
  'matchAnalysis.band.ambitious': 'Correspondance ambitieuse',
  'matchAnalysis.enrichmentTitle': 'Ajouter une expérience manquante (facultatif)',
  'matchAnalysis.enrichmentDescription': 'Ajoute uniquement une expérience réelle absente de ton CV. Les trois écarts les plus importants apparaissent en premier.',
  'matchAnalysis.enrichmentQuestion': 'As-tu une expérience professionnelle réelle qui répond à cette exigence ?',
  'matchAnalysis.enrichmentAnswer': 'Décris uniquement ce que tu as réellement fait',
  'matchAnalysis.enrichmentKind': 'Type d’expérience',
  'matchAnalysis.enrichmentAdd': 'Ajouter cette expérience et mettre à jour',
  'matchAnalysis.enrichmentDuplicateFailure': 'Cette information figure déjà dans ton CV. Ta correspondance précédente est conservée.',
  'matchAnalysis.enrichmentInvalidFailure': 'Décris ton expérience ou ignore cette question. Ta correspondance précédente est conservée.',
  'notFound.title': 'Page introuvable',
  'notFound.description': 'La page demandée n’existe pas.',
  'notFound.return': 'Revenir à l’accueil',
  'safetyNet.title': 'Un problème est survenu',
  'safetyNet.explanation': 'Cette page a cessé de fonctionner. Tes documents restent dans ce navigateur : recharge la page pour reprendre là où tu en étais.',
  'safetyNet.reload': 'Recharger',
  'safetyNet.returnToDocuments': 'Revenir à mes documents',
  'resumeReview.preview': 'Aperçu de ton CV',
  'resumeReview.description': 'Relis le document. Ouvre l’éditeur lorsque tu souhaites modifier quelque chose.',
  'resumeReview.hideEntry': 'Masquer l’expérience',
  'resumeReview.restoreEntry': 'Restaurer l’expérience',
  'resumeReview.edit': 'Modifier le CV',
  'resumeReview.close': 'Fermer l’éditeur',
  'resumeReview.contacts': 'Identité et coordonnées',
  'resumeReview.recovery': 'Éléments masqués',
  'resumeReview.order': 'Ordre des rubriques',
  'resumeReview.hidden': 'Contenu masqué',
  'resumeReview.omitted': 'Pas repris dans ce CV',
  'resumeReview.restore': 'Ajouter au CV',
  'resumeReview.emptyRecovery': 'Tout le contenu de ton CV est déjà inclus.',
  'resumeReview.localContacts': 'Ton identité et tes coordonnées restent dans ton navigateur et ne sont jamais envoyées au service de rédaction.',
  'resumeReview.condense': 'Proposer une version plus courte',
  'resumeReview.changeJobPosting': 'Changer d’offre d’emploi',
  'resumeReview.proposal': 'Proposition de version courte',
  'resumeReview.proposalDescription': 'Ton CV actuel reste inchangé jusqu’à ce que tu acceptes cette proposition.',
  'resumeReview.accept': 'Accepter la version courte',
  'resumeReview.reject': 'Garder la version actuelle',
  'resumeReview.checking': 'Vérification du document actuel…',
  'resumeReview.validating': 'Vérification de la rubrique modifiée…',
  'resumeReview.condensing': 'Préparation d’une proposition plus courte…',
  'resumeReview.unchecked': 'Le nombre de pages de cette version n’a pas été vérifié.',
  'resumeReview.shortening': 'Raccourcissement du CV…',
  'resumeReview.reviewHidden': 'Voir le contenu masqué',
  'resumeReview.hiddenByReduction': 'Masqué pour tenir sur la page',
  'resumeReview.section.value-proposition': 'Profil',
  'resumeReview.section.experiences': 'Expérience',
  'resumeReview.section.skills': 'Compétences',
  'resumeReview.section.education': 'Formation',
  'resumeReview.section.certifications': 'Certifications',
  'resumeReview.section.languages': 'Langues',
  'resumeReview.section.projects': 'Projets',
  'resumeReview.saved': 'CV mis à jour.',
  'resumeReview.hiddenNotice': 'Contenu masqué dans le CV.',
  'resumeReview.restored': 'Contenu restauré.',
  'resumeReview.ordered': 'Ordre mis à jour.',
  'resumeReview.usability': 'Peux-tu candidater avec ce PDF sans le restructurer ?',
  'resumeReview.usable': 'Oui, utilisable tel quel',
  'resumeReview.needsRewriting': 'Non, il doit être restructuré',
  'resumeReview.usabilityRecorded': 'Merci. Seule ta réponse a été enregistrée, jamais le contenu de ton CV.',
  'resumePreview.photo': 'Photo facultative',
  'resumePreview.photoInvalid': 'Choisis une image PNG, JPEG ou WebP de moins de 1 Mo.',
  'resumePreview.photoAdd': 'Ajouter une photo',
  'resumePreview.photoChange': 'Changer la photo',
  'resumePreview.photoRemove': 'Retirer',
  'resumePreview.photoHint': 'PNG, JPEG ou WebP, moins de 1 Mo.',
  'resumePreview.title': 'Aperçu et export',
  'resumePreview.pending': 'Préparation et vérification du PDF actuel…',
  'resumePreview.download': 'Télécharger le PDF',
  'resumePreview.page': 'Page',
  'resumePreview.textVersion': 'Lire le texte du document',
  'resumePreview.previewTitle': 'Aperçu du CV',
  'resumePreview.downloaded': 'PDF transmis à ton navigateur pour téléchargement.',
  'resumePreview.unsupported-content': 'Corrige ou confirme les modifications professionnelles non étayées avant le téléchargement.',
  'resumePreview.fullName': 'Nom complet',
  'resumePreview.detectedName': 'Repris de ton CV, vérifie l’orthographe.',
  'resumePreview.missing-identity': 'Ajoute ton nom complet pour télécharger le PDF.',
  'resumePreview.missing-contact': 'Ajoute une adresse e-mail ou un numéro de téléphone dans les coordonnées.',
  'resumePreview.stale-layout': 'Le document a changé. Attends l’aperçu actuel avant de télécharger.',
  'resumePreview.paused': 'Ferme l’éditeur pour télécharger le PDF actuel.',
  'resumePreview.copiedExperiences': 'Expériences reprises telles quelles',
  'pageBudget.fitsOne': 'Tient sur une page.',
  'pageBudget.fitsTwo': 'Tient sur deux pages.',
  'pageBudget.overflow': 'Ton CV fait {pageCount} pages, deux au maximum.',
  'pageBudget.proposalOverflow': 'Cette proposition dépasse encore deux pages.',
  'pageBudget.shorten': 'Raccourcir le CV',
} as const satisfies TranslationCatalog

export type Locale = 'en' | 'fr'

export type Localization = Readonly<{
  locale: Locale
  preferencePersistenceError: 'unavailable' | null
  readiness: 'pending' | 'ready'
  selectLocale: (locale: Locale) => void
  translate: (key: TranslationKey) => string
}>

export type LocalizationResult =
  | Readonly<{ ok: true; value: Localization }>
  | Readonly<{ ok: false; error: 'provider-missing' }>

type LocaleState = Pick<Localization, 'locale' | 'preferencePersistenceError' | 'readiness'>
type BrowserStorageResult<TValue> =
  | Readonly<{ ok: true; value: TValue }>
  | Readonly<{ ok: false; error: 'unavailable' }>

const catalogs: Readonly<Record<Locale, TranslationCatalog>> = {
  en: englishCatalog,
  fr: frenchCatalog,
}
const defaultLocale: Locale = 'en'
const localeStorageKey = 'honest-resume-locale'
const pendingLocaleState = {
  locale: defaultLocale,
  preferencePersistenceError: null,
  readiness: 'pending',
} as const satisfies LocaleState
const LocalizationContext = createContext<Localization | null>(null)

export function LocalizationProvider({ children }: Readonly<{ children: ReactNode }>) {
  const [localeState, setLocaleState] = useState<LocaleState>(pendingLocaleState)
  useEffect(() => {
    setLocaleState(readInitialLocale())
  }, [])
  return (
    <LocalizationContext.Provider value={{
      ...localeState,
      selectLocale: (selectedLocale) => {
        selectLocale({ selectedLocale, setLocaleState })
      },
      translate: (key) => readTranslation({ locale: localeState.locale, key }),
    }}>
      {children}
    </LocalizationContext.Provider>
  )
}

export function useLocalization() {
  const localization = useContext(LocalizationContext)
  if (localization === null) return missingProviderResult
  return { ok: true, value: localization } as const
}

export const defaultDocumentTitle = englishCatalog['brand.name']
export const localizationUnavailableMessage = englishCatalog['locale.unavailable']

export function LocalizationFailure() {
  return <p role="alert">{localizationUnavailableMessage}</p>
}

function readInitialLocale(): LocaleState {
  const storedLocale = readStoredLocale()
  if (storedLocale.ok && storedLocale.value !== null) {
    return createReadyLocaleState({ locale: storedLocale.value, persistenceError: null })
  }
  return createReadyLocaleState({
    locale: readSupportedLocale({ languages: navigator.languages }),
    persistenceError: storedLocale.ok ? null : storedLocale.error,
  })
}

function readStoredLocale(): BrowserStorageResult<Locale | null> {
  try {
    const storedLocale = localStorage.getItem(localeStorageKey)
    return { ok: true, value: parseLocale({ value: storedLocale }) }
  } catch {
    return { ok: false, error: 'unavailable' }
  }
}

function readSupportedLocale({ languages }: Readonly<{ languages: readonly string[] }>): Locale {
  for (const language of languages) {
    const [languageCode] = language.toLowerCase().split('-')
    const locale = parseLocale({ value: languageCode })
    if (locale !== null) return locale
  }
  return defaultLocale
}

function parseLocale({ value }: Readonly<{ value: string | null | undefined }>): Locale | null {
  return value === 'en' || value === 'fr' ? value : null
}

function selectLocale({
  selectedLocale,
  setLocaleState,
}: Readonly<{
  selectedLocale: Locale
  setLocaleState: (state: LocaleState) => void
}>) {
  const persistenceResult = storeLocale({ selectedLocale })
  setLocaleState(createReadyLocaleState({
    locale: selectedLocale,
    persistenceError: persistenceResult.ok ? null : persistenceResult.error,
  }))
}

function storeLocale({
  selectedLocale,
}: Readonly<{ selectedLocale: Locale }>): BrowserStorageResult<undefined> {
  try {
    localStorage.setItem(localeStorageKey, selectedLocale)
    return { ok: true, value: undefined }
  } catch {
    return { ok: false, error: 'unavailable' }
  }
}

function createReadyLocaleState({
  locale,
  persistenceError,
}: Readonly<{
  locale: Locale
  persistenceError: LocaleState['preferencePersistenceError']
}>): LocaleState {
  return { locale, preferencePersistenceError: persistenceError, readiness: 'ready' }
}

/** Both catalogs are complete at compile time, so a key always has its translation. */
function readTranslation({ locale, key }: Readonly<{ locale: Locale; key: TranslationKey }>) {
  return catalogs[locale][key]
}

const missingProviderResult = {
  ok: false,
  error: 'provider-missing',
} as const satisfies LocalizationResult
