/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAnalyticsRouteImport } from './routes/api.analytics'
import { Route as ApiJobRequirementExtractionRouteImport } from './routes/api.job-requirement-extraction'
import { Route as ApiMatchAnalysisRouteImport } from './routes/api.match-analysis'
import { Route as ApiResumeClaimValidationRouteImport } from './routes/api.resume-claim-validation'
import { Route as ApiResumeClaimWritingRouteImport } from './routes/api.resume-claim-writing'
import { Route as ApiSourceProfileExtractionRouteImport } from './routes/api.source-profile-extraction'
import { Route as ApiTailoredResumePdfRouteImport } from './routes/api.tailored-resume-pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: '/api/analytics',
  path: '/api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobRequirementExtractionRoute =
  ApiJobRequirementExtractionRouteImport.update({
    id: '/api/job-requirement-extraction',
    path: '/api/job-requirement-extraction',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMatchAnalysisRoute = ApiMatchAnalysisRouteImport.update({
  id: '/api/match-analysis',
  path: '/api/match-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResumeClaimValidationRoute =
  ApiResumeClaimValidationRouteImport.update({
    id: '/api/resume-claim-validation',
    path: '/api/resume-claim-validation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiResumeClaimWritingRoute = ApiResumeClaimWritingRouteImport.update({
  id: '/api/resume-claim-writing',
  path: '/api/resume-claim-writing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSourceProfileExtractionRoute =
  ApiSourceProfileExtractionRouteImport.update({
    id: '/api/source-profile-extraction',
    path: '/api/source-profile-extraction',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTailoredResumePdfRoute = ApiTailoredResumePdfRouteImport.update({
  id: '/api/tailored-resume-pdf',
  path: '/api/tailored-resume-pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/job-requirement-extraction': typeof ApiJobRequirementExtractionRoute
  '/api/match-analysis': typeof ApiMatchAnalysisRoute
  '/api/resume-claim-validation': typeof ApiResumeClaimValidationRoute
  '/api/resume-claim-writing': typeof ApiResumeClaimWritingRoute
  '/api/source-profile-extraction': typeof ApiSourceProfileExtractionRoute
  '/api/tailored-resume-pdf': typeof ApiTailoredResumePdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/job-requirement-extraction': typeof ApiJobRequirementExtractionRoute
  '/api/match-analysis': typeof ApiMatchAnalysisRoute
  '/api/resume-claim-validation': typeof ApiResumeClaimValidationRoute
  '/api/resume-claim-writing': typeof ApiResumeClaimWritingRoute
  '/api/source-profile-extraction': typeof ApiSourceProfileExtractionRoute
  '/api/tailored-resume-pdf': typeof ApiTailoredResumePdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/job-requirement-extraction': typeof ApiJobRequirementExtractionRoute
  '/api/match-analysis': typeof ApiMatchAnalysisRoute
  '/api/resume-claim-validation': typeof ApiResumeClaimValidationRoute
  '/api/resume-claim-writing': typeof ApiResumeClaimWritingRoute
  '/api/source-profile-extraction': typeof ApiSourceProfileExtractionRoute
  '/api/tailored-resume-pdf': typeof ApiTailoredResumePdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/analytics'
    | '/api/job-requirement-extraction'
    | '/api/match-analysis'
    | '/api/resume-claim-validation'
    | '/api/resume-claim-writing'
    | '/api/source-profile-extraction'
    | '/api/tailored-resume-pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/analytics'
    | '/api/job-requirement-extraction'
    | '/api/match-analysis'
    | '/api/resume-claim-validation'
    | '/api/resume-claim-writing'
    | '/api/source-profile-extraction'
    | '/api/tailored-resume-pdf'
  id:
    | '__root__'
    | '/'
    | '/api/analytics'
    | '/api/job-requirement-extraction'
    | '/api/match-analysis'
    | '/api/resume-claim-validation'
    | '/api/resume-claim-writing'
    | '/api/source-profile-extraction'
    | '/api/tailored-resume-pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAnalyticsRoute: typeof ApiAnalyticsRoute
  ApiJobRequirementExtractionRoute: typeof ApiJobRequirementExtractionRoute
  ApiMatchAnalysisRoute: typeof ApiMatchAnalysisRoute
  ApiResumeClaimValidationRoute: typeof ApiResumeClaimValidationRoute
  ApiResumeClaimWritingRoute: typeof ApiResumeClaimWritingRoute
  ApiSourceProfileExtractionRoute: typeof ApiSourceProfileExtractionRoute
  ApiTailoredResumePdfRoute: typeof ApiTailoredResumePdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics': {
      id: '/api/analytics'
      path: '/api/analytics'
      fullPath: '/api/analytics'
      preLoaderRoute: typeof ApiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/job-requirement-extraction': {
      id: '/api/job-requirement-extraction'
      path: '/api/job-requirement-extraction'
      fullPath: '/api/job-requirement-extraction'
      preLoaderRoute: typeof ApiJobRequirementExtractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/match-analysis': {
      id: '/api/match-analysis'
      path: '/api/match-analysis'
      fullPath: '/api/match-analysis'
      preLoaderRoute: typeof ApiMatchAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resume-claim-validation': {
      id: '/api/resume-claim-validation'
      path: '/api/resume-claim-validation'
      fullPath: '/api/resume-claim-validation'
      preLoaderRoute: typeof ApiResumeClaimValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resume-claim-writing': {
      id: '/api/resume-claim-writing'
      path: '/api/resume-claim-writing'
      fullPath: '/api/resume-claim-writing'
      preLoaderRoute: typeof ApiResumeClaimWritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/source-profile-extraction': {
      id: '/api/source-profile-extraction'
      path: '/api/source-profile-extraction'
      fullPath: '/api/source-profile-extraction'
      preLoaderRoute: typeof ApiSourceProfileExtractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tailored-resume-pdf': {
      id: '/api/tailored-resume-pdf'
      path: '/api/tailored-resume-pdf'
      fullPath: '/api/tailored-resume-pdf'
      preLoaderRoute: typeof ApiTailoredResumePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAnalyticsRoute: ApiAnalyticsRoute,
  ApiJobRequirementExtractionRoute: ApiJobRequirementExtractionRoute,
  ApiMatchAnalysisRoute: ApiMatchAnalysisRoute,
  ApiResumeClaimValidationRoute: ApiResumeClaimValidationRoute,
  ApiResumeClaimWritingRoute: ApiResumeClaimWritingRoute,
  ApiSourceProfileExtractionRoute: ApiSourceProfileExtractionRoute,
  ApiTailoredResumePdfRoute: ApiTailoredResumePdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
