export const resumeReviewCopy = {
  en: {
    previewTitle: 'Tailored Resume preview', preview: 'Preview your resume', description: 'Review the document first. Open the editor only when you want to change something.',
    hideEntry: 'Hide experience', restoreEntry: 'Restore experience', print: 'Print current resume', edit: 'Edit resume', close: 'Close editor', contacts: 'Identity and contact details', recovery: 'Restore content',
    order: 'Section order', hidden: 'Hidden content', omitted: 'Source content not included', restore: 'Restore source content',
    emptyRecovery: 'All supported source content is included.', localContacts: 'Identity and contact details stay in your browser and are never sent for professional rewriting.',
    condense: 'Propose a shorter version', checkLayout: 'Check page count', proposal: 'Shorter version proposal',
    proposalDescription: 'Your current resume stays unchanged until you accept this proposal.', accept: 'Accept shorter version', reject: 'Keep current version',
    checking: 'Checking the current document…', validating: 'Checking the edited section…', condensing: 'Preparing a shorter proposal…',
    unchecked: 'Page count has not been checked for this version.', fits: 'The current version fits within two pages.',
    overflow: 'This version exceeds two pages. Try a shorter proposal, or choose content to hide in the editor. Nothing is removed automatically.',
    unavailable: 'Page count is unavailable. Your content is preserved; try the check again.',
    unsupported: 'Some edits need your confirmation or correction before export.',
    failure: 'The operation could not complete. Your current content is preserved.',
    'renew-consent': 'Renew processing consent before trying again.', retry: 'Try the operation again.',
    'correct-content': 'Correct the unsupported content or explicitly attest it.', 'retry-current-draft': 'The document changed. Try again with the current version.',
    'missing-identity': 'Add your name.', 'missing-contact': 'Add an email address or phone number.',
    'unsupported-content': 'Correct or attest unsupported edits.', 'layout-unavailable': 'Check the page count before export.',
    'stale-layout': 'Check page count again after your edits.',
    'value-proposition': 'Summary', experiences: 'Experience', skills: 'Skills', education: 'Education',
    certifications: 'Certifications', languages: 'Languages', projects: 'Projects', analysis: 'Review match analysis',
    saved: 'Resume updated.', hiddenNotice: 'Content hidden from the resume.', restored: 'Content restored.', ordered: 'Order updated.',
    regenerate: 'Regenerate resume', regenerateWarning: 'Regenerating replaces your manual edits. Continue?',
    usability: 'Can you apply with this PDF without restructuring it?', usable: 'Yes, usable as is',
    needsRewriting: 'No, it needs structural rewriting', usabilityRecorded: 'Thank you. Only your answer was recorded, never your resume content.',
  },
  fr: {
    previewTitle: 'Aperçu du CV adapté', preview: 'Aperçu de ton CV', description: 'Relis le document. Ouvre l’éditeur lorsque tu souhaites modifier quelque chose.',
    hideEntry: 'Masquer l’expérience', restoreEntry: 'Restaurer l’expérience', print: 'Imprimer le CV actuel', edit: 'Modifier le CV', close: 'Fermer l’éditeur', contacts: 'Identité et coordonnées', recovery: 'Restaurer du contenu',
    order: 'Ordre des rubriques', hidden: 'Contenu masqué', omitted: 'Contenu source non inclus', restore: 'Restaurer le contenu source',
    emptyRecovery: 'Tout le contenu source attesté est inclus.', localContacts: 'Ton identité et tes coordonnées restent dans ton navigateur et ne sont jamais envoyées pour reformulation professionnelle.',
    condense: 'Proposer une version plus courte', checkLayout: 'Vérifier le nombre de pages', proposal: 'Proposition de version courte',
    proposalDescription: 'Ton CV actuel reste inchangé jusqu’à ce que tu acceptes cette proposition.', accept: 'Accepter la version courte', reject: 'Garder la version actuelle',
    checking: 'Vérification du document actuel…', validating: 'Vérification de la rubrique modifiée…', condensing: 'Préparation d’une proposition plus courte…',
    unchecked: 'Le nombre de pages de cette version n’a pas été vérifié.', fits: 'La version actuelle tient sur deux pages maximum.',
    overflow: 'Cette version dépasse deux pages. Essaie une proposition plus courte ou choisis le contenu à masquer dans l’éditeur. Rien n’est supprimé automatiquement.',
    unavailable: 'Le nombre de pages est indisponible. Ton contenu est conservé ; relance la vérification.',
    unsupported: 'Certaines modifications nécessitent ta confirmation ou une correction avant l’export.',
    failure: 'L’opération n’a pas abouti. Ton contenu actuel est conservé.',
    'renew-consent': 'Renouvelle ton consentement au traitement avant de réessayer.', retry: 'Réessaie l’opération.',
    'correct-content': 'Corrige le contenu non étayé ou atteste-le explicitement.', 'retry-current-draft': 'Le document a changé. Réessaie avec la version actuelle.',
    'missing-identity': 'Ajoute ton nom.', 'missing-contact': 'Ajoute une adresse e-mail ou un numéro de téléphone.',
    'unsupported-content': 'Corrige ou atteste les modifications non étayées.', 'layout-unavailable': 'Vérifie le nombre de pages avant l’export.',
    'stale-layout': 'Vérifie à nouveau le nombre de pages après tes modifications.',
    'value-proposition': 'Profil', experiences: 'Expérience', skills: 'Compétences', education: 'Formation',
    certifications: 'Certifications', languages: 'Langues', projects: 'Projets', analysis: 'Consulter l’analyse de correspondance',
    saved: 'CV mis à jour.', hiddenNotice: 'Contenu masqué dans le CV.', restored: 'Contenu restauré.', ordered: 'Ordre mis à jour.',
    regenerate: 'Régénérer le CV', regenerateWarning: 'La régénération remplace tes modifications manuelles. Continuer ?',
    usability: 'Peux-tu candidater avec ce PDF sans le restructurer ?', usable: 'Oui, utilisable tel quel',
    needsRewriting: 'Non, il doit être restructuré', usabilityRecorded: 'Merci. Seule ta réponse a été enregistrée, jamais le contenu de ton CV.',
  },
} as const

export type ResumeReviewCopy = typeof resumeReviewCopy[keyof typeof resumeReviewCopy]
